<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title>Hello</title>
        <link rel="stylesheet" href="http://meyerweb.com/eric/tools/css/reset/reset.css" type="text/css" media="screen" charset="utf-8">
        <style>
        html, body {
            font-size: 11px;
            line-height: 15px;
        }
        div#source, div#result {
            text-wrap: pre-line;
            font-family: Sans;
            width: 50%;
            height: 100%;
        }
        div#source {
            float: left;
        }
        div#result {
            float: right;
            font-size: 9px;
            font-family: Monospace;
        }
        div pre {
            padding: 1em;
        }
        a {
            color: inherit;
            text-decoration: inherit;
        }
        a:hover {
            background-color: yellow;
        }
        </style>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript" charset="utf-8">
            $(document).ready(function() {
            });
        </script>
    </head>
    <body>

<div id="source">
<pre>

'\" <a href="?word=t">t</span>
.\"
.\" <a href="?word=You">You</span> <a href="?word=may">may</span> <a href="?word=distribute">distribute</span> <a href="?word=under">under</span> <a href="?word=the">the</span> <a href="?word=terms">terms</span> <a href="?word=of">of</span> <a href="?word=the">the</span> <a href="?word=GNU">GNU</span> <a href="?word=General">General</span> <a href="?word=Public">Public</span>
.\" <a href="?word=License">License</span> <a href="?word=as">as</span> <a href="?word=specified">specified</span> <a href="?word=in">in</span> <a href="?word=the">the</span> <a href="?word=file">file</span> <a href="?word=COPYING">COPYING</span> <a href="?word=that">that</span> <a href="?word=comes">comes</span> <a href="?word=with">with</span> <a href="?word=the">the</span>
.\" <a href="?word=man">man</span>-<a href="?word=db">db</span> <a href="?word=distribution">distribution</span>.
.\"
.\" <a href="?word=Sat">Sat</span> <a href="?word=Nov">Nov</span> <a href="?word=27">27</span>
.\"
.<a href="?word=pc">pc</span>
.<a href="?word=TH">TH</span> <a href="?word=print">print</span> <a href="?word=soapbox">soapbox</span> "<a href="?word=2009">2009</span>-<a href="?word=11">11</span>-<a href="?word=28">28</span>" "<a href="?word=1">1</span>.<a href="?word=0">0</span>" "<a href="?word=print">print</span>"
.<a href="?word=SH">SH</span> <a href="?word=manuals">manuals</span>, <a href="?word=man">man</span> <a href="?word=pages">pages</span>
.<a href="?word=I">I</span> <a href="?word=according">according</span> <a href="?word=to">to</span> <a href="?word=the">the</span> <a href="?word=mmm">mmm</span>, <a href="?word=software">software</span> <a href="?word=has">has</span> <a href="?word=two">two</span> <a href="?word=faces">faces</span>, <a href="?word=both">both</span> <a href="?word=as">as</span> <a href="?word=important">important</span>. <a href="?word=the">the</span> <a href="?word=code">code</span>
.<a href="?word=I">I</span> <a href="?word=speaks">speaks</span> <a href="?word=to">to</span> <a href="?word=the">the</span> <a href="?word=machine">machine</span>, <a href="?word=and">and</span> <a href="?word=the">the</span> <a href="?word=documentation">documentation</span> ``<a href="?word=tells">tells</span> <a href="?word=its">its</span> <a href="?word=story">story</span> <a href="?word=to">to</span> <a href="?word=the">the</span> <a href="?word=human">human</span>
.<a href="?word=I">I</span> <a href="?word=user">user</span>.''

<a href="?word=The">The</span> <a href="?word=following">following</span> <a href="?word=is">is</span> <a href="?word=also">also</span> <a href="?word=from">from</span> <a href="?word=the">the</span> <a href="?word=fanzine">fanzine</span> <a href="?word=I">I</span>'<a href="?word=m">m</span> <a href="?word=talking">talking</span> <a href="?word=about">about</span>. <a href="?word=It">It</span>'<a href="?word=s">s</span> <a href="?word=a">a</span> <a href="?word=perhaps">perhaps</span>
<a href="?word=convoluted">convoluted</span> <a href="?word=way">way</span> <a href="?word=of">of</span> <a href="?word=saying">saying</span> <a href="?word=that">that</span> <a href="?word=there">there</span>'<a href="?word=s">s</span> <a href="?word=a">a</span> <a href="?word=difference">difference</span> <a href="?word=between">between</span> <a href="?word=the">the</span> <a href="?word=documents">documents</span> <a href="?word=that">that</span>
<a href="?word=keep">keep</span> <a href="?word=track">track</span> <a href="?word=of">of</span> <a href="?word=the">the</span> <a href="?word=changes">changes</span> <a href="?word=in">in</span> <a href="?word=a">a</span> <a href="?word=piece">piece</span> <a href="?word=of">of</span> <a href="?word=software">software</span> <a href="?word=over">over</span> <a href="?word=time">time</span>, <a href="?word=and">and</span> <a href="?word=the">the</span> <a href="?word=documents">documents</span>
<a href="?word=that">that</span> <a href="?word=show">show</span> <a href="?word=how">how</span> <a href="?word=a">a</span> <a href="?word=piece">piece</span> <a href="?word=of">of</span> <a href="?word=software">software</span> <a href="?word=is">is</span> <a href="?word=used">used</span>, <a href="?word=even">even</span> <a href="?word=if">if</span> <a href="?word=they">they</span> <a href="?word=sometimes">sometimes</span> <a href="?word=get">get</span> <a href="?word=lumped">lumped</span>
<a href="?word=together">together</span>. <a href="?word=Texinfo">Texinfo</span> <a href="?word=is">is</span> <a href="?word=just">just</span> <a href="?word=another">another</span> <a href="?word=documentation">documentation</span> <a href="?word=format">format</span> <a href="?word=that">that</span> <a href="?word=some">some</span> <a href="?word=people">people</span> <a href="?word=seem">seem</span>
<a href="?word=to">to</span> <a href="?word=prefer">prefer</span>.

.<a href="?word=I">I</span> <a href="?word=in">in</span> <a href="?word=the">the</span> <a href="?word=gnu">gnu</span> <a href="?word=coding">coding</span> <a href="?word=standards">standards</span>, <a href="?word=the">the</span> <a href="?word=terms">terms</span> <a href="?word=documentation">documentation</span> <a href="?word=and">and</span> <a href="?word=manual">manual</span> <a href="?word=practically">practically</span>
.<a href="?word=I">I</span> <a href="?word=mean">mean</span> <a href="?word=the">the</span> <a href="?word=same">same</span> <a href="?word=thing">thing</span>. <a href="?word=specifically">specifically</span>, <a href="?word=a">a</span> <a href="?word=manual">manual</span> <a href="?word=is">is</span> <a href="?word=a">a</span> <a href="?word=texinfo">texinfo</span> <a href="?word=file">file</span>, <a href="?word=and">and</span>
.<a href="?word=I">I</span> <a href="?word=documentation">documentation</span> <a href="?word=includes">includes</span> <a href="?word=manuals">manuals</span> <a href="?word=and">and</span> <a href="?word=other">other</span> <a href="?word=things">things</span> <a href="?word=like">like</span> <a href="?word=NEWS">NEWS</span> <a href="?word=files">files</span> <a href="?word=and">and</span> <a href="?word=change">change</span>
.<a href="?word=I">I</span> <a href="?word=logs">logs</span>. <a href="?word=in">in</span> <a href="?word=practice">practice</span>, <a href="?word=the">the</span> <a href="?word=latter">latter</span> <a href="?word=term">term</span> <a href="?word=practically">practically</span> <a href="?word=takes">takes</span> <a href="?word=the">the</span> <a href="?word=place">place</span> <a href="?word=of">of</span> <a href="?word=the">the</span> <a href="?word=former">former</span>.
.<a href="?word=I">I</span> <a href="?word=regarding">regarding</span> <a href="?word=unix">unix</span> <a href="?word=man">man</span> <a href="?word=pages">pages</span>, <a href="?word=gnu">gnu</span> <a href="?word=suggests">suggests</span> <a href="?word=that">that</span> -<a href="?word=if">if</span> <a href="?word=adequate">adequate</span>- <a href="?word=help2man">help2man</span> <a href="?word=be">be</span> <a href="?word=used">used</span> <a href="?word=to">to</span>
.<a href="?word=I">I</span> <a href="?word=extract">extract</span> <a href="?word=a">a</span> <a href="?word=man">man</span> <a href="?word=page">page</span> <a href="?word=from">from</span> <a href="?word=the">the</span> <a href="?word=texinfo">texinfo</span> <a href="?word=file">file</span>. <a href="?word=unlike">unlike</span> <a href="?word=man">man</span> <a href="?word=pages">pages</span>, <a href="?word=gnu">gnu</span> <a href="?word=manuals">manuals</span> <a href="?word=should">should</span>
.<a href="?word=I">I</span> <a href="?word=have">have</span> <a href="?word=a">a</span> ``<a href="?word=coherent">coherent</span> <a href="?word=topic">topic</span>''. <a href="?word=as">as</span> <a href="?word=an">an</span> <a href="?word=example">example</span>, <a href="?word=the">the</span> <a href="?word=coding">coding</span> <a href="?word=standards">standards</span> <a href="?word=note">note</span> <a href="?word=that">that</span> <a href="?word=diff">diff</span>
.<a href="?word=I">I</span> <a href="?word=and">and</span> <a href="?word=diff3">diff3</span> <a href="?word=are">are</span> <a href="?word=both">both</span> <a href="?word=covered">covered</span> <a href="?word=in">in</span> <a href="?word=a">a</span> <a href="?word=single">single</span> <a href="?word=manual">manual</span>, <a href="?word=whereas">whereas</span> <a href="?word=there">there</span> <a href="?word=are">are</span> <a href="?word=two">two</span> <a href="?word=man">man</span>
.<a href="?word=I">I</span> <a href="?word=pages">pages</span>, <a href="?word=one">one</span> <a href="?word=for">for</span> <a href="?word=each">each</span> <a href="?word=command">command</span>.

<a href="?word=I">I</span> <a href="?word=think">think</span> <a href="?word=that">that</span> <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=funny">funny</span> <a href="?word=that">that</span> <a href="?word=they">they</span> <a href="?word=write">write</span> <a href="?word=implementation">implementation</span> <a href="?word=does">does</span> <a href="?word=not">not</span> <a href="?word=equal">equal</span>
<a href="?word=documentation">documentation</span>. <a href="?word=I">I</span> <a href="?word=guess">guess</span> <a href="?word=that">that</span> <a href="?word=sometimes">sometimes</span> <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=hard">hard</span> <a href="?word=to">to</span> <a href="?word=take">take</span> <a href="?word=distance">distance</span>:

.<a href="?word=I">I</span> <a href="?word=the">the</span> <a href="?word=people">people</span> <a href="?word=of">of</span> <a href="?word=gnu">gnu</span> <a href="?word=distinguish">distinguish</span> <a href="?word=between">between</span> <a href="?word=the">the</span> <a href="?word=way">way</span> <a href="?word=in">in</span> <a href="?word=which">which</span> <a href="?word=a">a</span> <a href="?word=program">program</span> <a href="?word=was">was</span> <a href="?word=built">built</span>,
.<a href="?word=I">I</span> <a href="?word=and">and</span> <a href="?word=the">the</span> <a href="?word=way">way</span> <a href="?word=in">in</span> <a href="?word=which">which</span> <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=used">used</span>. <a href="?word=they">they</span> <a href="?word=warn">warn</span> <a href="?word=about">about</span> <a href="?word=modelling">modelling</span> <a href="?word=the">the</span> <a href="?word=documentation">documentation</span>
.<a href="?word=I">I</span> <a href="?word=after">after</span> <a href="?word=the">the</span> <a href="?word=software">software</span>:

.<a href="?word=B">B</span> <a href="?word=programmers">programmers</span> <a href="?word=tend">tend</span> <a href="?word=to">to</span> <a href="?word=carry">carry</span> <a href="?word=over">over</span> <a href="?word=the">the</span> <a href="?word=structure">structure</span> <a href="?word=of">of</span> <a href="?word=the">the</span> <a href="?word=program">program</span> <a href="?word=as">as</span> <a href="?word=the">the</span>
.<a href="?word=B">B</span> <a href="?word=structure">structure</span> <a href="?word=for">for</span> <a href="?word=its">its</span> <a href="?word=documentation">documentation</span>. <a href="?word=but">but</span> <a href="?word=this">this</span> <a href="?word=structure">structure</span> <a href="?word=is">is</span> <a href="?word=not">not</span> <a href="?word=necessarily">necessarily</span>
.<a href="?word=B">B</span> <a href="?word=good">good</span> <a href="?word=for">for</span> <a href="?word=explaining">explaining</span> <a href="?word=how">how</span> <a href="?word=to">to</span> <a href="?word=use">use</span> <a href="?word=the">the</span> <a href="?word=program">program</span> [...] <a href="?word=learn">learn</span> <a href="?word=to">to</span> <a href="?word=notice">notice</span> <a href="?word=when">when</span>
.<a href="?word=B">B</span> <a href="?word=you">you</span> <a href="?word=have">have</span> <a href="?word=unthinkingly">unthinkingly</span> <a href="?word=structured">structured</span> <a href="?word=the">the</span> <a href="?word=documentation">documentation</span> <a href="?word=like">like</span> <a href="?word=the">the</span>
.<a href="?word=B">B</span> <a href="?word=implementation">implementation</span>, <a href="?word=stop">stop</span> <a href="?word=yourself">yourself</span>, <a href="?word=and">and</span> <a href="?word=look">look</span> <a href="?word=for">for</span> <a href="?word=better">better</span> <a href="?word=alternatives">alternatives</span>.

.<a href="?word=I">I</span> <a href="?word=the">the</span> <a href="?word=coding">coding</span> <a href="?word=standards">standards</span> <a href="?word=advise">advise</span> <a href="?word=authors">authors</span> <a href="?word=to">to</span> <a href="?word=approach">approach</span> <a href="?word=users">users</span> <a href="?word=pedagogically">pedagogically</span>, <a href="?word=thinking">thinking</span>
.<a href="?word=I">I</span> <a href="?word=about">about</span> ``<a href="?word=the">the</span> <a href="?word=concepts">concepts</span> <a href="?word=and">and</span> <a href="?word=questions">questions</span> <a href="?word=that">that</span> <a href="?word=a">a</span> <a href="?word=user">user</span> <a href="?word=will">will</span> <a href="?word=have">have</span> <a href="?word=in">in</span> <a href="?word=mind">mind</span> <a href="?word=when">when</span> <a href="?word=reading">reading</span>
.<a href="?word=I">I</span> <a href="?word=it">it</span>.'' <a href="?word=what">what</span>'<a href="?word=s">s</span> <a href="?word=more">more</span>, <a href="?word=the">the</span> <a href="?word=manuals">manuals</span> <a href="?word=that">that</span> <a href="?word=they">they</span> <a href="?word=write">write</span> <a href="?word=should">should</span> <a href="?word=admit">admit</span> <a href="?word=two">two</span> <a href="?word=types">types</span> <a href="?word=of">of</span>
.<a href="?word=I">I</span> <a href="?word=reading">reading</span>: <a href="?word=tutorial">tutorial</span> <a href="?word=and">and</span> <a href="?word=reference">reference</span>. <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=interesting">interesting</span> <a href="?word=to">to</span> <a href="?word=note">note</span> <a href="?word=that">that</span> <a href="?word=by">by</span> <a href="?word=tutorial">tutorial</span> <a href="?word=they">they</span>
.<a href="?word=I">I</span> <a href="?word=mean">mean</span> <a href="?word=something">something</span> <a href="?word=that">that</span> <a href="?word=a">a</span> <a href="?word=user">user</span> <a href="?word=may">may</span> <a href="?word=want">want</span> <a href="?word=to">to</span> <a href="?word=read">read</span> <a href="?word=straight">straight</span> <a href="?word=through">through</span>.

<a href="?word=in">in</span> <a href="?word=this">this</span> <a href="?word=essay">essay</span>, <a href="?word=code">code</span> <a href="?word=is">is</span> <a href="?word=the">the</span> <a href="?word=textual">textual</span> <a href="?word=aspect">aspect</span> <a href="?word=of">of</span> <a href="?word=computer">computer</span> <a href="?word=technology">technology</span> <a href="?word=that">that</span> <a href="?word=may">may</span> <a href="?word=be">be</span>
<a href="?word=loaded">loaded</span> <a href="?word=up">up</span> <a href="?word=on">on</span> <a href="?word=a">a</span> <a href="?word=text">text</span> <a href="?word=editor">editor</span> <a href="?word=and">and</span> <a href="?word=easily">easily</span> <a href="?word=changed">changed</span>. <a href="?word=i">i</span>'<a href="?word=m">m</span> <a href="?word=consciously">consciously</span> <a href="?word=avoiding">avoiding</span> <a href="?word=any">any</span>
<a href="?word=discussion">discussion</span> <a href="?word=on">on</span> <a href="?word=the">the</span> <a href="?word=subject">subject</span> <a href="?word=of">of</span> <a href="?word=text">text</span> <a href="?word=editors">editors</span> -- <a href="?word=jot">jot</span> <a href="?word=down">down</span> <a href="?word=your">your</span> <a href="?word=edits">edits</span> <a href="?word=on">on</span> <a href="?word=a">a</span> <a href="?word=piece">piece</span> <a href="?word=of">of</span>
<a href="?word=paper">paper</span> <a href="?word=and">and</span> <a href="?word=then">then</span> <a href="?word=write">write</span> <a href="?word=them">them</span> <a href="?word=to">to</span> <a href="?word=newfile">newfile</span> <a href="?word=with">with</span> <a href="?word=echo">echo</span>. <a href="?word=what">what</span>'<a href="?word=s">s</span> <a href="?word=important">important</span> <a href="?word=to">to</span> <a href="?word=me">me</span> <a href="?word=is">is</span> <a href="?word=that">that</span>
<a href="?word=this">this</span> <a href="?word=be">be</span> <a href="?word=easily">easily</span> <a href="?word=accomplished">accomplished</span>. <a href="?word=with">with</span> <a href="?word=enough">enough</span> <a href="?word=time">time</span> <a href="?word=and">and</span> <a href="?word=energy">energy</span>, <a href="?word=anyone">anyone</span> <a href="?word=could">could</span> <a href="?word=write">write</span>
<a href="?word=interesting">interesting</span> <a href="?word=code">code</span>. <a href="?word=the">the</span> <a href="?word=best">best</span> <a href="?word=project">project</span> <a href="?word=would">would</span> <a href="?word=be">be</span> <a href="?word=if">if</span> <a href="?word=my">my</span> <a href="?word=grandmother">grandmother</span> <a href="?word=took">took</span> <a href="?word=the">the</span> <a href="?word=time">time</span> <a href="?word=to">to</span>
<a href="?word=re">re</span>-<a href="?word=write">write</span> <a href="?word=the">the</span> <a href="?word=linux">linux</span> <a href="?word=kernel">kernel</span> <a href="?word=from">from</span> <a href="?word=scratch">scratch</span>, <a href="?word=and">and</span> <a href="?word=if">if</span> <a href="?word=she">she</span> <a href="?word=kept">kept</span> <a href="?word=a">a</span> <a href="?word=record">record</span> <a href="?word=of">of</span> <a href="?word=her">her</span>
<a href="?word=reflections">reflections</span> <a href="?word=about">about</span> <a href="?word=code">code</span>. <a href="?word=as">as</span> <a href="?word=much">much</span> <a href="?word=as">as</span> <a href="?word=i">i</span> <a href="?word=like">like</span> <a href="?word=pierre">pierre</span> <a href="?word=menard">menard</span>, <a href="?word=this">this</span> <a href="?word=is">is</span> <a href="?word=not">not</span> <a href="?word=feasible">feasible</span>.
<a href="?word=the">the</span> <a href="?word=processes">processes</span> <a href="?word=of">of</span> <a href="?word=code">code</span> <a href="?word=should">should</span> <a href="?word=be">be</span> <a href="?word=manageable">manageable</span> <a href="?word=without">without</span> <a href="?word=the">the</span> <a href="?word=need">need</span> <a href="?word=of">of</span> <a href="?word=resorting">resorting</span> <a href="?word=to">to</span>
<a href="?word=too">too</span> <a href="?word=much">much</span> <a href="?word=external">external</span> <a href="?word=technical">technical</span> <a href="?word=support">support</span>. <a href="?word=this">this</span> <a href="?word=means">means</span> <a href="?word=that">that</span> <a href="?word=code">code</span> <a href="?word=is">is</span> <a href="?word=relative">relative</span>. <a href="?word=what">what</span>'<a href="?word=s">s</span>
<a href="?word=code">code</span> <a href="?word=for">for</span> <a href="?word=some">some</span> <a href="?word=will">will</span> <a href="?word=not">not</span> <a href="?word=be">be</span> <a href="?word=code">code</span> <a href="?word=for">for</span> <a href="?word=others">others</span>.

<a href="?word=when">when</span> <a href="?word=it">it</span> <a href="?word=comes">comes</span> <a href="?word=down">down</span> <a href="?word=to">to</span> <a href="?word=it">it</span>, <a href="?word=this">this</span> <a href="?word=means">means</span> <a href="?word=that">that</span> <a href="?word=code">code</span> <a href="?word=is">is</span> <a href="?word=text">text</span> <a href="?word=written">written</span> <a href="?word=in">in</span> <a href="?word=one">one</span> <a href="?word=of">of</span> <a href="?word=the">the</span>
<a href="?word=computer">computer</span> <a href="?word=languages">languages</span>. <a href="?word=code">code</span> <a href="?word=is">is</span> <a href="?word=the">the</span> <a href="?word=active">active</span> <a href="?word=practice">practice</span> <a href="?word=of">of</span> <a href="?word=altering">altering</span> <a href="?word=half">half</span>-<a href="?word=understood">understood</span>
<a href="?word=text">text</span> <a href="?word=files">files</span>. <a href="?word=code">code</span> <a href="?word=are">are</span> <a href="?word=the">the</span> <a href="?word=static">static</span> <a href="?word=characters">characters</span> <a href="?word=that">that</span> <a href="?word=silently">silently</span> <a href="?word=stare">stare</span> <a href="?word=back">back</span> <a href="?word=at">at</span> <a href="?word=you">you</span>,
<a href="?word=and">and</span> <a href="?word=that">that</span> <a href="?word=will">will</span> <a href="?word=not">not</span> <a href="?word=even">even</span> <a href="?word=you">you</span> <a href="?word=give">give</span> <a href="?word=the">the</span> <a href="?word=illusion">illusion</span> <a href="?word=that">that</span> <a href="?word=you">you</span>'<a href="?word=re">re</span> <a href="?word=double">double</span>-<a href="?word=guessing">guessing</span> <a href="?word=a">a</span>
<a href="?word=machine">machine</span>. <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=always">always</span> <a href="?word=evident">evident</span> <a href="?word=that">that</span> <a href="?word=someone">someone</span> <a href="?word=else">else</span> <a href="?word=was">was</span> <a href="?word=there">there</span> <a href="?word=before">before</span> <a href="?word=you">you</span>, <a href="?word=and">and</span> <a href="?word=that">that</span>
<a href="?word=that">that</span> <a href="?word=person">person</span> <a href="?word=was">was</span> <a href="?word=sloppy">sloppy</span>. <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=just">just</span> <a href="?word=a">a</span> <a href="?word=matter">matter</span> <a href="?word=of">of</span> <a href="?word=playing">playing</span> <a href="?word=along">along</span> <a href="?word=and">and</span> <a href="?word=locating">locating</span> <a href="?word=those">those</span>
<a href="?word=three">three</span> <a href="?word=characters">characters</span> <a href="?word=in">in</span> <a href="?word=a">a</span> <a href="?word=text">text</span> <a href="?word=file">file</span> <a href="?word=that">that</span> <a href="?word=will">will</span> <a href="?word=make">make</span> <a href="?word=all">all</span> <a href="?word=the">the</span> <a href="?word=difference">difference</span> <a href="?word=on">on</span> <a href="?word=whether">whether</span>
<a href="?word=your">your</span> <a href="?word=computer">computer</span> <a href="?word=can">can</span> <a href="?word=display">display</span> <a href="?word=postscript">postscript</span> <a href="?word=or">or</span> <a href="?word=whether">whether</span> <a href="?word=it">it</span> <a href="?word=will">will</span> <a href="?word=keep">keep</span> <a href="?word=that">that</span> <a href="?word=as">as</span> <a href="?word=a">a</span> <a href="?word=secret">secret</span>
<a href="?word=to">to</span> <a href="?word=itself">itself</span>. 

<a href="?word=my">my</span> <a href="?word=one">one</span> <a href="?word=year">year</span> <a href="?word=experience">experience</span> <a href="?word=as">as</span> <a href="?word=a">a</span> <a href="?word=software">software</span> <a href="?word=writer">writer</span> <a href="?word=has">has</span> <a href="?word=not">not</span> <a href="?word=been">been</span> <a href="?word=so">so</span> <a href="?word=nice">nice</span>, <a href="?word=but">but</span> <a href="?word=really">really</span>
<a href="?word=you">you</span> <a href="?word=should">should</span> <a href="?word=ask">ask</span> <a href="?word=someone">someone</span> <a href="?word=else">else</span> <a href="?word=with">with</span> <a href="?word=more">more</span> <a href="?word=experience">experience</span>. <a href="?word=i">i</span>'<a href="?word=ve">ve</span> <a href="?word=only">only</span> <a href="?word=worked">worked</span> <a href="?word=a">a</span> <a href="?word=little">little</span> <a href="?word=as">as</span>
<a href="?word=a">a</span> <a href="?word=freelancer">freelancer</span> (<a href="?word=whatever">whatever</span> <a href="?word=that">that</span> <a href="?word=means">means</span>) <a href="?word=on">on</span> <a href="?word=some">some</span> <a href="?word=random">random</span> <a href="?word=websites">websites</span>. <a href="?word=i">i</span>'<a href="?word=ve">ve</span> <a href="?word=been">been</span> <a href="?word=learning">learning</span>
<a href="?word=on">on</span> <a href="?word=the">the</span> <a href="?word=job">job</span> (<a href="?word=whatever">whatever</span> <a href="?word=that">that</span> <a href="?word=means">means</span>).

<a href="?word=there">there</span> <a href="?word=are">are</span> <a href="?word=probably">probably</span> <a href="?word=other">other</span> <a href="?word=ways">ways</span> <a href="?word=of">of</span> <a href="?word=saying">saying</span> <a href="?word=it">it</span>, <a href="?word=but">but</span> <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=also">also</span> <a href="?word=fine">fine</span> <a href="?word=to">to</span> <a href="?word=say">say</span> <a href="?word=that">that</span>
<a href="?word=i">i</span>'<a href="?word=ve">ve</span> <a href="?word=been">been</span> <a href="?word=bored">bored</span>.  <a href="?word=i">i</span> <a href="?word=don">don</span>'<a href="?word=t">t</span> <a href="?word=know">know</span> <a href="?word=why">why</span>. <a href="?word=there">there</span> <a href="?word=have">have</span> <a href="?word=been">been</span> <a href="?word=projects">projects</span> <a href="?word=i">i</span>'<a href="?word=m">m</span> <a href="?word=not">not</span> <a href="?word=ashamed">ashamed</span>
<a href="?word=of">of</span>, <a href="?word=but">but</span> <a href="?word=most">most</span> <a href="?word=of">of</span> <a href="?word=the">the</span> <a href="?word=time">time</span> <a href="?word=it">it</span> <a href="?word=hasn">hasn</span>'<a href="?word=t">t</span> <a href="?word=been">been</span> <a href="?word=like">like</span> <a href="?word=that">that</span>. <a href="?word=i">i</span> <a href="?word=wish">wish</span> <a href="?word=i">i</span> <a href="?word=could">could</span> <a href="?word=say">say</span> <a href="?word=i">i</span> <a href="?word=was">was</span>
<a href="?word=young">young</span> <a href="?word=i">i</span> <a href="?word=needed">needed</span> <a href="?word=the">the</span> <a href="?word=money">money</span> <a href="?word=but">but</span> <a href="?word=i">i</span>'<a href="?word=m">m</span> <a href="?word=not">not</span> <a href="?word=even">even</span> <a href="?word=that">that</span> <a href="?word=young">young</span> <a href="?word=anymore">anymore</span>. <a href="?word=health">health</span> <a href="?word=insurance">insurance</span>
<a href="?word=and">and</span> <a href="?word=that">that</span> <a href="?word=type">type</span> <a href="?word=of">of</span> <a href="?word=stuff">stuff</span> <a href="?word=is">is</span> <a href="?word=a">a</span> <a href="?word=work">work</span> <a href="?word=of">of</span> <a href="?word=fiction">fiction</span>. <a href="?word=my">my</span> <a href="?word=life">life</span> <a href="?word=is">is</span> <a href="?word=only">only</span> <a href="?word=as">as</span> <a href="?word=long">long</span> <a href="?word=as">as</span> <a href="?word=my">my</span>
<a href="?word=computer">computer</span>'<a href="?word=s">s</span> <a href="?word=life">life</span>.

<a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=depressing">depressing</span> <a href="?word=to">to</span> <a href="?word=see">see</span> <a href="?word=that">that</span> <a href="?word=some">some</span> <a href="?word=cliches">cliches</span> <a href="?word=are">are</span> <a href="?word=true">true</span>. <a href="?word=the">the</span> <a href="?word=offices">offices</span> <a href="?word=of">of</span> <a href="?word=lab">lab</span> <a href="?word=rats">rats</span>
<a href="?word=typing">typing</span> <a href="?word=looking">looking</span> <a href="?word=for">for</span> <a href="?word=the">the</span> <a href="?word=key">key</span> <a href="?word=of">of</span> <a href="?word=the">the</span> <a href="?word=cookie">cookie</span>, <a href="?word=waiting">waiting</span> <a href="?word=to">to</span> <a href="?word=be">be</span> <a href="?word=rewarded">rewarded</span> <a href="?word=with">with</span> <a href="?word=a">a</span>
<a href="?word=cookie">cookie</span>, <a href="?word=and">and</span> <a href="?word=kept">kept</span> <a href="?word=awake">awake</span> <a href="?word=with">with</span> <a href="?word=coffee">coffee</span>. <a href="?word=i">i</span> <a href="?word=could">could</span> <a href="?word=have">have</span> <a href="?word=passed">passed</span> <a href="?word=out">out</span> <a href="?word=in">in</span> <a href="?word=front">front</span> <a href="?word=of">of</span> <a href="?word=the">the</span>
<a href="?word=computer">computer</span> <a href="?word=and">and</span> <a href="?word=no">no</span> <a href="?word=one">one</span> <a href="?word=would">would</span> <a href="?word=have">have</span> <a href="?word=noticed">noticed</span>. <a href="?word=the">the</span> <a href="?word=feeling">feeling</span> <a href="?word=that">that</span> <a href="?word=no">no</span> <a href="?word=one">one</span> <a href="?word=knows">knows</span> <a href="?word=what">what</span>
<a href="?word=they">they</span>'<a href="?word=re">re</span> <a href="?word=doing">doing</span>. <a href="?word=the">the</span> <a href="?word=obscure">obscure</span> <a href="?word=files">files</span> <a href="?word=that">that</span> <a href="?word=you">you</span> <a href="?word=can">can</span> <a href="?word=find">find</span> <a href="?word=inside">inside</span> <a href="?word=of">of</span> <a href="?word=some">some</span> <a href="?word=computers">computers</span>.
<a href="?word=what">what</span> <a href="?word=i">i</span> <a href="?word=would">would</span> <a href="?word=do">do</span> <a href="?word=is">is</span> <a href="?word=open">open</span> <a href="?word=them">them</span> <a href="?word=for">for</span> <a href="?word=as">as</span> <a href="?word=long">long</span> <a href="?word=as">as</span> <a href="?word=i">i</span>'<a href="?word=d">d</span> <a href="?word=stand">stand</span> <a href="?word=it">it</span>, <a href="?word=close">close</span> <a href="?word=my">my</span> <a href="?word=eyes">eyes</span>, <a href="?word=press">press</span>
<a href="?word=some">some</span> <a href="?word=random">random</span> <a href="?word=keys">keys</span>, <a href="?word=close">close</span> <a href="?word=them">them</span> <a href="?word=and">and</span> <a href="?word=try">try</span> <a href="?word=to">to</span> <a href="?word=forget">forget</span> <a href="?word=about">about</span> <a href="?word=it">it</span>. <a href="?word=there">there</span>'<a href="?word=s">s</span> <a href="?word=determinacy">determinacy</span>
<a href="?word=in">in</span> <a href="?word=software">software</span> <a href="?word=insofar">insofar</span> <a href="?word=as">as</span> <a href="?word=you">you</span> <a href="?word=can">can</span> <a href="?word=work">work</span> <a href="?word=like">like</span> <a href="?word=this">this</span> <a href="?word=and">and</span> <a href="?word=nothing">nothing</span> <a href="?word=breaks">breaks</span>.

<a href="?word=i">i</span> <a href="?word=wish">wish</span> <a href="?word=i">i</span> <a href="?word=could">could</span> <a href="?word=live">live</span> <a href="?word=in">in</span> <a href="?word=a">a</span> <a href="?word=mountain">mountain</span> <a href="?word=and">and</span> <a href="?word=contemplate">contemplate</span> <a href="?word=my">my</span> <a href="?word=mark">mark</span>-<a href="?word=up">up</span>.  <a href="?word=i">i</span> <a href="?word=wish">wish</span> <a href="?word=it">it</span> <a href="?word=was">was</span>,
<a href="?word=but">but</span> <a href="?word=it">it</span> <a href="?word=can">can</span>'<a href="?word=t">t</span> <a href="?word=be">be</span> <a href="?word=and">and</span> <a href="?word=it">it</span> <a href="?word=isn">isn</span>'<a href="?word=t">t</span> <a href="?word=only">only</span> <a href="?word=about">about</span> <a href="?word=the">the</span> <a href="?word=code">code</span>. <a href="?word=if">if</span> <a href="?word=it">it</span> <a href="?word=was">was</span> <a href="?word=only">only</span> <a href="?word=about">about</span> <a href="?word=the">the</span>
<a href="?word=code">code</span>, <a href="?word=i">i</span> <a href="?word=wouldn">wouldn</span>'<a href="?word=t">t</span> <a href="?word=need">need</span> <a href="?word=to">to</span> <a href="?word=go">go</span> <a href="?word=out">out</span> <a href="?word=of">of</span> <a href="?word=my">my</span> <a href="?word=room">room</span>. <a href="?word=i">i</span> <a href="?word=don">don</span>'<a href="?word=t">t</span> <a href="?word=know">know</span> <a href="?word=what">what</span> <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=about">about</span>, <a href="?word=and">and</span> <a href="?word=i">i</span>
<a href="?word=don">don</span>'<a href="?word=t">t</span> <a href="?word=know">know</span> <a href="?word=what">what</span> <a href="?word=i">i</span>'<a href="?word=m">m</span> <a href="?word=talking">talking</span> <a href="?word=about">about</span>. <a href="?word=this">this</span> <a href="?word=is">is</span> <a href="?word=the">the</span> <a href="?word=point">point</span> <a href="?word=where">where</span> <a href="?word=i">i</span> <a href="?word=start">start</span> <a href="?word=to">to</span> <a href="?word=have">have</span>
<a href="?word=problems">problems</span> <a href="?word=finishing">finishing</span> <a href="?word=my">my</span> <a href="?word=sentences">sentences</span>. <a href="?word=likewise">likewise</span>, <a href="?word=this">this</span> <a href="?word=type">type</span> <a href="?word=of">of</span> <a href="?word=media">media</span> <a href="?word=work">work</span> <a href="?word=is">is</span> <a href="?word=complete">complete</span>
<a href="?word=nonsense">nonsense</span>. <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=absurd">absurd</span> <a href="?word=that">that</span> <a href="?word=i">i</span> <a href="?word=can">can</span>'<a href="?word=t">t</span> <a href="?word=find">find</span> <a href="?word=a">a</span> <a href="?word=job">job</span>, <a href="?word=and">and</span> <a href="?word=that">that</span> <a href="?word=i">i</span> <a href="?word=can">can</span>'<a href="?word=t">t</span> <a href="?word=hold">hold</span> <a href="?word=on">on</span> <a href="?word=to">to</span> <a href="?word=the">the</span>
<a href="?word=jobs">jobs</span> <a href="?word=that">that</span> <a href="?word=i">i</span> <a href="?word=hate">hate</span>.

<a href="?word=after">after</span> <a href="?word=one">one</span> <a href="?word=year">year</span> <a href="?word=of">of</span> <a href="?word=writing">writing</span> <a href="?word=software">software</span>, <a href="?word=it">it</span>'<a href="?word=s">s</span> <a href="?word=good">good</span> <a href="?word=to">to</span> <a href="?word=go">go</span> <a href="?word=back">back</span> <a href="?word=to">to</span> <a href="?word=the">the</span> <a href="?word=first">first</span> <a href="?word=things">things</span> <a href="?word=i">i</span>
<a href="?word=wrote">wrote</span>. <a href="?word=maybe">maybe</span> <a href="?word=there">there</span> <a href="?word=is">is</span> <a href="?word=something">something</span> <a href="?word=of">of</span> <a href="?word=crawling">crawling</span> <a href="?word=into">into</span> <a href="?word=my">my</span> <a href="?word=bed">bed</span> <a href="?word=and">and</span> <a href="?word=pulling">pulling</span> <a href="?word=up">up</span> <a href="?word=the">the</span>
<a href="?word=covers">covers</span> <a href="?word=about">about</span> <a href="?word=it">it</span>. <a href="?word=probably">probably</span> <a href="?word=not">not</span>. <a href="?word=i">i</span>'<a href="?word=m">m</span> <a href="?word=just">just</span> <a href="?word=happy">happy</span>. <a href="?word=it">it</span> <a href="?word=was">was</span> <a href="?word=great">great</span> <a href="?word=to">to</span> <a href="?word=have">have</span> <a href="?word=imagined">imagined</span>
<a href="?word=an">an</span> <a href="?word=introductory">introductory</span> <a href="?word=perl">perl</span> <a href="?word=manual">manual</span> <a href="?word=where">where</span> <a href="?word=the">the</span> <a href="?word=examples">examples</span> <a href="?word=and">and</span> <a href="?word=exercises">exercises</span> <a href="?word=deal">deal</span> <a href="?word=with">with</span>
<a href="?word=generative">generative</span> <a href="?word=groff">groff</span> <a href="?word=mark">mark</span>-<a href="?word=up">up</span>.
</pre>
</div>

<div id="result">
<pre>
{{ ptx }}
</pre>
</div>
    </body>
</html>
