%def extrahead():
    <style type="text/css" media="screen">
        div#container {
            width: 100%;
        }
        div#intro {
            padding: 1em;
            background-color: white;
            float: left;
            width: 30em;
            margin-right: 1em;
margin-top: 1em;
        }
        div#experiments {
            padding: 1em;
            background-color: white;
            float: left;
            width: 30em;
            margin-right: 1em;
margin-top: 1em;
        }
        div#colophon {
            width: 30em;
            float: left;
            padding: 1em;
            background-color: white;
            float: left;
        }
        div#container h3 {
            margin-top: 1em;
        }
    </style>
%end


%rebase templates/compact background=background, extrahead=extrahead, title='By data we mean, a publication', oneliner='Intentions behind this set of prototypes and experiments.'


<div id="container">
<div id="intro">
    <h1 id="by-data-we-mean-a-publication">By data we mean, a publication</h1>
    <h2 id="the-facts">The facts</h2>
    <p>This publication documents the 12th edition of the Verbindigen/Jonctions festival which took place in Brussels from 21 to 29 November 2009.</p>
    <p>This bi-annual multidisciplinary festival is organized by Constant, Association for Art and Media, with the intent to gather around the same table a large and diverse public - radio makers, artists, software programmers, academics, Linux users, interface designers, urban explorers, performance artists, technicians, lawyers and others – and to offer them the chance of experiencing each other’s practices and experimental reflections on technological culture and free licenses.</p>
    <p>This edition was hosted at 17 rue de la Senne, in an open public space that Constant was invited to share with other organizations as part of the one-year program implemented by Ischa Tallieu and Jan Verbruggen with the intention of enhancing an abandoned building in the heart of Brussels.</p>
    <p>Through a series of conferences, work sessions and performances, three topics of discussion were proposed and explored:</p>
    <ul>
    <li><strong>Shades of Grey Literature</strong> was an invitation to discover, play and worry about the mass of anonymous documents, commentaries and written traces which form the background of electronic and non-electronic communication; as it frames the relationship between machines and humans and the way humans relate through networks, who has the right to see, read, write or execute?</li>
    <li><strong>The Life and Nature of Data</strong> tried to answer the question: what is a data? To whom or what is it handed over or where does it come from? Each electronic transaction leaves a trace; profiling of users is done in the interest of marketeers and advertisers, for state surveillance or to control the workplace; different practices all based on the extraction of information from “data”, an ambiguous entity always ready to mutate, multiply and never loyal to its origins.<br /></li>
    <li><strong>Performative Instructions</strong> analysed codes and norms that put themselves or others in motion. Users and developers exchange information through bug reports and error messages and confront issues of responsibility and authority put in place through manuals, recipes, forms and other types of instructions.</li>
    </ul>
    <p>During the festival, the interventions varied from lectures discussing the ambiguity concealed in the Web language and in its abundant <em>grey literature</em> («Systemic Ambiguity» by Andrew Goffey and Matthew Fuller, «To Talk of Many Things» by Michael Moss) to a surgical analysis of the textual codes and standards of the Debian community («From Source Code to Text Code» by Christophe Lazaro); from a Soap Box annual report (by Ivan Monroy Lopez) to an on-line conversation of a software testing team in action («Fit for Purpose»); from a trans-disciplinary collaborative installation-performance around the usage of surveillance camera’s and software («Kaleidoscope, a genesis» by An Mertens) to a conference weighing the charm and value of privacy today («Amidst the Golden Age of Privacy» by Seda Gürses); from a philosophical and socio-anthropological theater adventure («Smatch(1)» by Dominique Roodthooft) to a time-travel into the land of the paratext («From Textual Scholarship to the Study of Tradition» by Jurgen Pieters) to a presentation of internet applications for the critique of Web 2.0 («GooDiff» by Alexandre Delaunoy) or webpage generating theatrical scripts from Wikipedia entries ( «Epicpedia» by Annemieke and Marloes van der Hoek).</p>
    <p>The three topics mentioned above and the different ways they were developed by the participants inspired us with the idea of a publication that breaks with the tradition of the printed catalog and is inspired by the interconnected architecture of the internet and to the possibilities offered by digital media in terms of writing/editing a text or a book.</p>
    <h2 id="the-inspirational-sources">The inspirational sources</h2>
    <h3 id="text-vs-document">Text vs Document</h3>
    <p><em>Convoluut</em> <em>Term uit de codicologie en (analytische) bibliografie voor een boek, waarin handschriften of drukken, die wat hun ontstaan betreft niets met elkaar te maken hebben, door een bezitter zijn samengebonden. Zo bevat de codex UB Leiden, Ltk. 191, zes verschillende handschriften: &quot;Ferguut, Floris ende Blancefloer, Der historien bloeme, Esopet, Die bediedenisse vander missen in dietsche en Die dietsche doctrinael. Indien het vanaf het begin af aan de bedoeling was de verschillende teksten in één handschrift te bundelen, spreekt men van een verzamelhandschrift.&quot;</em> LIT: BDI; Brongers; Gorp; Hiller; MEW. [W. Kuiper]<sup><a href="#fn1" class="footnoteRef" id="fnref1">1</a></sup></p>
    <p>A <em>codex</em> (or <em>convoluut</em> or <em>verzamelhandschrift</em><sup><a href="#fn2" class="footnoteRef" id="fnref2">2</a></sup>) was a manuscript in which a miscellany of various texts were bound together, sometimes without any apparent connection. It was a sort of compendium or family book full of material and a repertoire that could be used on different occasions. It appears to be quite common in Flanders in the Middle Ages. The binding was rather poor, the appearance business-like; the texts were generally written on two columns and the bottom of each page showed the number of lines, since at that time the copyists were paid per line. This literary form seems to find an echo in the verb &quot;to convolute&quot; that means to coil up into a twisted shape, to roll up, but also to intertwine, to twist and turn, to make complicated<sup><a href="#fn3" class="footnoteRef" id="fnref3">3</a></sup>.</p>
    <p>This attempt to preserve documents that were generally not supposed to be made public or published, transforming them into a sort of journal of family life and events, reminded us of a sort of collection of <em>ante litteram</em>, <em>grey litterature</em> texts. It was certainly very inspiring because it seemed to coincide with our actual problem of witnessing in the most adequate, but at the same time interesting way possible an event such as the Verbindingen/Jonctions 12. It gave us the idea of experimenting with the material we had (in the widest sense of the term) instead of more traditionally make the texts of the lectures accessible to the public via a printed publication. Several questions haunted us.</p>
    <h3 id="which-form-should-take-the-publication">Which form should take the publication?</h3>
    <p>Definitely on-line, since the network is the place par excellence of new textual experimentations (e-readers, hypertexts, wikis, pads...).</p>
    <p>What does a multi-disciplinary festival and its publication exactly mean in terms of production of <em>grey litterature</em>?</p>
    <p>We started looking for, collecting and classifying all the documents of every kind and form that were connected to the event. At first, it was just a very generic research, writing down the locations, talking and exchanging mails with Constant members, looking into the folder where we kept a big part of the administration and production documents related to the festival (invoices, tickets, forms, certificates, notes, etc.), losing ourselfves into the intricate maze of the Constant websites to trace all the materials scattered on the Web (photos, videos, codes, reports, etc.). We began to realise that there was much more than solely the texts that the participants sent us after the festival, as agreed, to appear in our publication. Was this &quot;much more&quot;, this V/J12 <em>grey litterature</em>, interesting enough to be shown? In what manner could it affect the way in which the reader looks at a festival publication? Could the writing production of an author exist without being surrounded by a dense web of &quot;grey&quot; documents?</p>
    <p>Of course we are not the only ones troubled by these issues. An example that is worth mentioning is the beautiful work published on the occasion of the <em>Musée Précaire Albinet</em> project (The Precarious Museum Albinet) by Thomas Hirschhorn in 2004. The Swiss artist proposed the construction of a precarious building in Aubervilliers, a suburb of Paris in France, with the aim of exhibiting major Western art works of the twentieth century such as those of Marcel Duchamp, Salvador Dalí and Andy Warhol. The &quot;museum&quot; was built and operated with the help of the inhabitants. Throughout the project development, Thomas Hirschhorn and the Laboratoires d'Aubervilliers kept the documents related to this collective work: the set of written texts exchanged with the partners, the traces of various meetings between the artistic team and the citizens as well as the production inherent to the operational aspect of the museum and the newspaper articles. The result was an important archive that was reworked in the catalog as an annotated chronology put into perspective by the artist<sup><a href="#fn4" class="footnoteRef" id="fnref4">4</a></sup>. Almost all the (textual and visual) documentation is represented and classified according to genre, date, sender, recipient, subject. These documents form a dense and fascinating amalgam that tells the history of the project from within.</p>
    <h3 id="beyond-the-text">Beyond the text</h3>
    <p>Alongside the work of collecting the documents, there was also the idea of rethinking the essays and articles we received from the participants. While reading and re-reading these texts and watching them more closely, we observed that they seemed to contain another huge amount of &quot;material&quot; taking the shape of references, quotes, footnotes and hyperlinks. At that point, we felt like Alice falling down the rabbit hole and discovering a never-ending tunnel full of all kind of stuff<sup><a href="#fn5" class="footnoteRef" id="fnref5">5</a></sup>.</p>
    <p>The desire of going beyond (&quot;literary&quot;) codes and standards is therefore not a contemporary trend but is intrinsic to the very history of literature and language. Jurgen Pieters showed it beautifully in his analysis of the vision of Jerome McGann on the digital revolution and the way it affects the object &quot;book&quot;. Pieters' essay presents many references to various literary works very far from each other in terms of time and genre: from Dante's anthology <em>La Vita Nuova</em><sup><a href="#fn6" class="footnoteRef" id="fnref6">6</a></sup> in which the comments of the author are mixed with his own poems in a perfect alternation of prose and poetry, to <em>The Arcades Project</em> (<em>Das Passagen-Werk</em>, 1927-1940)<sup><a href="#fn7" class="footnoteRef" id="fnref7">7</a></sup>, an encyclopedic collection of writings on the city life of Paris in the 19th century, the lifelong project of Walter Benjamin.</p>
    <p>A unique case in the history of literature we stumbled on during our research, is represented by the <em>Shinkokinshû</em> (or new <em>kokinshû</em>), a Japanese anthology of poems (from the 12th century) in which the cohesion of the work is ensured not only by a linear structure, but also by an associative one<sup><a href="#fn8" class="footnoteRef" id="fnref8">8</a></sup>. Each unit in fact is linked to the other through different mechanisms: association by categories of images, by words that bear a common meaning established by the poetic tradition, by key words (or <em>kake kotoba</em>) that have a double meaning, or by pillow-words (or <em>makura-kotoba</em>), conventional epithets that form verses which refer to each other. This dense skein of connections and cross-references ping-ponging from one poem to the other creates a complex and heterogeneous system of reading levels.</p>
    <p>However, writers and avant-garde literary movements have sought new ways, opening the way for unpredictable reading experiences. Just think of the &quot;visual poems&quot; of Guillaume Apollinaire<sup><a href="#fn9" class="footnoteRef" id="fnref9">9</a></sup> or the <em>parole in libertà</em> (Free Words) proclaimed by the Italian Futurists<sup><a href="#fn10" class="footnoteRef" id="fnref10">10</a></sup> or the self-imposed constrained writing techniques of the members of the OULIPO (<em>OUvroir de LIttérature POtentielle</em>, roughly translated: 'workshop of potential literature')<sup><a href="#fn11" class="footnoteRef" id="fnref11">11</a></sup>.</p>
    <p>In the last century, the digital revolution and the advent of the Internet have certainly shaken the literary world as well as other artistic fields. Theorists and artists are pushed to rethink the idea of text, of narrative, of fiction, even of a book in its most concrete form. Moreover, the development of technology linked to electronic networks has offered them new tools for text processing, breaking through the classical &quot;horizontal structure&quot; of a publication in which more texts are put next to each other or of a narration presented in a follow-up. Thanks to hyperlinks, specific words become links to other texts, each of which is in turn accompanied by references and links to other texts, images, videos and all kinds of documentation. Each text is no longer secluded into the limited size of a page or into the limited number of pages of a book. The possibilities are multiplied and become endless. Hypertext<sup><a href="#fn12" class="footnoteRef" id="fnref12">12</a></sup> writing developed its own style of fiction<sup><a href="#fn13" class="footnoteRef" id="fnref13">13</a></sup>.</p>
    <h2 id="conclusions">Conclusions</h2>
    <p>This publication constitutes eventually a platform for experimentation. Even if we maybe didn't address all the issues in depth, still we hope to have given to the reader a series of possible paths to be further explored and to have opened up new interpretations and possibilities of building his own post-festival journey through a forest of many different documents and texts. We hope you will enjoy it.</p>
    <div class="footnotes">
        <hr />
        <ol>
            <li id="fn1"><p>1/ <a href="http://www.dbnl.org/tekst/bork001lett01_01/bork001lett01_01_0004.php#c164">http://www.dbnl.org/tekst/bork001lett01_01/bork001lett01_01_0004.php#c164</a> <a href="#fnref1" class="footnoteBackLink" title="Jump back to footnote 1">↩</a></p></li>
            <li id="fn2"><p>2/ <a href="http://nl.wikipedia.org/wiki/Hulthemse_handschrift">http://nl.wikipedia.org/wiki/Hulthemse_handschrift</a> <a href="#fnref2" class="footnoteBackLink" title="Jump back to footnote 2">↩</a></p></li>
            <li id="fn3"><p>3/ <a href="http://www.thefreedictionary.com/convolute">http://www.thefreedictionary.com/convolute</a> <a href="#fnref3" class="footnoteBackLink" title="Jump back to footnote 3">↩</a></p></li>
            <li id="fn4"><p>4/ <a href="http://archives.leslaboratoires.org/content/view/144/lang,en/">http://archives.leslaboratoires.org/content/view/144/lang,en/</a> <a href="#fnref4" class="footnoteBackLink" title="Jump back to footnote 4">↩</a></p></li>
            <li id="fn5"><p>5/ <a href="http://books.google.be/books?id=Y7sOAAAAIAAJ&amp;printsec=frontcover&amp;dq=alice+in+wonderland+down+the+rabbit+hole&amp;hl=en&amp;ei=glHGTrzTGsLn-gbkpakK&amp;sa=X&amp;oi=book_result&amp;ct=result&amp;resnum=5&amp;ved=0CEIQ6AEwBA#v=onepage&amp;q&amp;f=false">http://books.google.be/books?id=Y7sOAAAAIAAJ&amp;printsec=frontcover&amp;dq=alice+in+wonderland+down+the+rabbit+hole&amp;hl=en&amp;ei=glHGTrzTGsLn-gbkpakK&amp;sa=X&amp;oi=book_result&amp;ct=result&amp;resnum=5&amp;ved=0CEIQ6AEwBA#v=onepage&amp;q&amp;f=false</a> <a href="#fnref5" class="footnoteBackLink" title="Jump back to footnote 5">↩</a></p></li>
            <li id="fn6"><p>6/ [http://it.wikisource.org/wiki/Rime<em>%28Dante%29/XIV</em><em>Donne_ch%27avete_intelletto_d%27amore](http://it.wikisource.org/wiki/Rime</em>%28Dante%29/XIV__Donne_ch%27avete_intelletto_d%27amore) <a href="#fnref6" class="footnoteBackLink" title="Jump back to footnote 6">↩</a></p></li>
            <li id="fn7"><p>7/ <a href="http://www.thelemming.com/lemming/dissertation-web/home/arcades.html">http://www.thelemming.com/lemming/dissertation-web/home/arcades.html</a> <a href="#fnref7" class="footnoteBackLink" title="Jump back to footnote 7">↩</a></p></li>
            <li id="fn8"><p>8/ <a href="http://www.sengokudaimyo.com/miscellany/poetry.html">http://www.sengokudaimyo.com/miscellany/poetry.html</a> <a href="#fnref8" class="footnoteBackLink" title="Jump back to footnote 8">↩</a></p></li>
            <li id="fn9"><p>9/ <a href="http://en.wikipedia.org/wiki/File:Guillaume_Apollinaire_Calligramme.JPG">http://en.wikipedia.org/wiki/File:Guillaume_Apollinaire_Calligramme.JPG</a> <a href="#fnref9" class="footnoteBackLink" title="Jump back to footnote 9">↩</a></p></li>
            <li id="fn10"><p>10/ « Now imagine that a friend of yours, gifted with this kind of lyrical faculty, should find himself in a zone of intense life to recount his impressions. Do you know what your lyrical friend will do while he is still shocked?... He will begin by brutally destroying the syntax of his speech. He will not waste time in constructing periodic sentences. He could care less about punctuation or finding the right adjective. He desdains subtleties and shadings, and in haste he will assault your nerves with visual, auditory and olfactory sensations, just as their insistent pressure in him demands. The rush of steam-emotion will burst the steampipe of the sentence, the valves of punctuation, and the regular clamp of the adjective. Fistfuls of basic words without a conventional order. Only preoccupation of the narrator, to render all the vibrations of his &quot;I&quot;.» in «Distruzione della sintassi/Immaginazione senza fili/ Parole in libertà», by Filippo Tommaso Marinetti, in <em>Modernism: an anthology</em> (ed. Lawrence Rainey), Blackwell Publishing, 2005. <a href="#fnref10" class="footnoteBackLink" title="Jump back to footnote 10">↩</a></p></li>
            <li id="fn11"><p>11/ <a href="http://www.oulipo.net">http://www.oulipo.net</a> <a href="#fnref11" class="footnoteBackLink" title="Jump back to footnote 11">↩</a></p></li>
            <li id="fn12"><p>12/ A term coined by Ted Nelson in 1963. It refers to an electronic text with references to other texts that the reader can immediately access. Hypertext is the underlying concept defining the structure of the World Wide Web. <a href="#fnref12" class="footnoteBackLink" title="Jump back to footnote 12">↩</a></p></li>
            <li id="fn13"><p>13/ An example among many: Shelley Jackson's <em>Patchwork girl</em>. <a href="#fnref13" class="footnoteBackLink" title="Jump back to footnote 13">↩</a></p></li>
        </ol>
    </div>
</div>

<div id="experiments">
    <h2 id="the-experiments">The experiments</h2>
    <p>When we left behind the theoretical research and we started working directly with the material we had collected, we found ourselves in the middle of a battle field between <em>convoluut</em> and indexed documents, between <em>grey litterature</em> and original essays, between paratext<sup><a href="#fn14" class="footnoteRef" id="fnref14">14</a></sup>, intertext and hypertext. Different experiments started to take form and to become the real body of this publication.</p>
    <h3 id="micromacro">Micro/Macro</h3>
    <p>Following the theme of the 12th edition of the festival, we decided to show all the <em>grey literature</em> then produced, in the form of a timeline that allowed us to see the greater and lesser dense periods in the production of the festival and to analyse and compare the metadata embodied by each document. This works on a &quot;macro&quot; scale (the festival) but also on a &quot;micro&quot; scale represented by two specific events, the lectures «Systemic Ambiguity» by Andrew Goffey and Matthew Fuller and «To Talk of Many Things» by Michael Moss and how they were used to produce a textual re-mix. A second timeline features the annotation of the video recording of Michael Moss lecture during an Active Archive workshop.</p>
    <p>(il faut parler aussi l'experimentation de Stéphanie et Alex sur le macro/micro)</p>
    <h3 id="re-mixing-up">Re-Mixing up</h3>
    <p>We wanted to explore how it is possible to make visible some of the associations that a human mind makes while writing or reading a text by criss-crossing texts. These &quot;correspondances&quot; are often shown adding footnotes with references to other essays or creating direct hyperlinks to other webpages. Even though intertextuality, the allusion or influence by a prior text<sup><a href="#fn15" class="footnoteRef" id="fnref15">15</a></sup>, has always been present in <em>any</em> text<sup><a href="#fn16" class="footnoteRef" id="fnref16">16</a></sup>, the use of free licenses in the texts of V/J12 invites us to explore and experiment it more deeply. By willingly releasing their texts under licenses allowing derivative works, the authors of the text gave us the opportunity to perform hybridations. And the result of our remix can be considered as an invitation to others to realize their own and share them in return. We started to play with some texts, trying to push the boundaries of interpretation. What happens in fact when two texts apparently very different from each other, but with many common points at a second reading, are brought together, mixed, smashed up? Do they suddenly acquire a completely different form and meaning? Isn't each text ambiguous in itself, being open to different interpretations and how can the notes and references it contains influence the process of reading and decoding it?</p>
    <p>We chose three different approaches that derived from the very nature of the texts: essays, report/testimony, discussion/personal annotations: * «To Talk of Many Systemic Ambiguity», in which «Systemic Ambiguity» by Andrew Goffey and Matthew Fuller and «To Talk of Many Things by Michael Moss are mixed together with the footnotes and the references present in «Systemic Ambiguity», creating an autonomous text, extremely rich, complex and understandable; * «KaleidoSmatch», in which «Kaleidoscope, a genesis» by An Mertens and «Smatch(1)» by Dominique Roodthooft are presented as a parallel narration about two different theatre experiences, sharing the layout and the use of images and hyperlinks; * «Fit the Annual Report on Purpose», in which «Fit for Purpose» by the FLOSS developers and «Soap Box annual report» by Ivan Monroy Lopez are carried out as a theatre piece in three acts with Ivan as a voiceover.</p>
    <p>The original texts are of course available on Constant's website. These remixes, however, reveal totally unexpected, new and playful interpretations of the originals. Of course, all of this was possible thanks to the fact that these texts are under a free artistic license. Can the use of free licenses represent a new frontier in terms of experimental writing? Or does it put even more in question the concept of &quot;original&quot; work? The results of our experimentations are surely not anymore what the texts were in the beginning. We didn't try to replicate them, we tried somehow to go through and beyond them, to enrich them with new possible reading patterns stimulated by the original texts.</p>
    <h3 id="nltk">NLTK</h3>
    <p>Using NLTK<sup><a href="#fn17" class="footnoteRef" id="fnref17">17</a></sup>, we want to observe what different results the computer can find when comparing texts than what human logic can. Therefore, we used the same couples of texts than in the remixes to have a different approach. Each couple can be filtered through three sorting methods: * by &quot;concordances&quot; (viewing in what context the same word appears in both texts); * by &quot;similar contexts&quot; (finding words sharing the same context in both texts); * by &quot;collocations&quot; (finding couples of words in both texts).</p>
    <h3 id="paracode">Paracode</h3>
    <p>The term paratext is coined by Gérard Genette in 1987. It gathers all the text elements around the text itself which are usually considered as secondary and sometimes optional (some elements of the paratext are added or removed from one edition to another). This &quot;grey&quot; text is &quot;a zone not only of transition but also of transaction: a privileged place of pragmatics and a strategy, of an influence on the public, an influence that [...] is at the service of a better reception for the text and a more pertinent reading of it.&quot; <sup><a href="#fn18" class="footnoteRef" id="fnref18">18</a></sup> In <em>Paratexts: Thresholds of Interpretation</em>, Genette draws up a list of all paratext elements of a book (fiction, non-fiction, poetry...). We are trying through the close-reading of a piece of software, written by Anne-Laure Buisson for V/J12, to find new paratext elements specific to the digital nature of a contemporary text, and more precisely, of a piece of code: a text which is supposed to be read by a specific public (sometimes the author himself), a text which has a precise function.</p>

    <div class="footnotes">
        <hr />
        <ol>
            <li id="fn14"><p>14/ « Paratext is a concept in litterary interpretation. The concept is that the work of the author (the main text) is surrounded by other text supplied by editors, printers and publishers. These added elements form a frame or a reference for the authorial text. » Wikipedia. <a href="http://en.wikipedia.org/wiki/Paratext">http://en.wikipedia.org/wiki/Paratext</a> <a href="#fnref14" class="footnoteBackLink" title="Jump back to footnote 14">↩</a></p></li>
            <li id="fn15"><p>15/ The term is first mentioned by Julia Kristeva in 1966. <a href="http://en.wikipedia.org/wiki/Intertextuality">http://en.wikipedia.org/wiki/Intertextuality</a> <a href="#fnref15" class="footnoteBackLink" title="Jump back to footnote 15">↩</a></p></li>
            <li id="fn16"><p>16/ Raymond Federman, &quot;Imagination as Plagiarism [An Unfinished Paper...]&quot;, <em>New Literary History</em>, Vol. 7, No. 3: &quot;Thinking in the Arts, Sciences, and Literature&quot;, Spring 1976, p. 563-578. <a href="#fnref16" class="footnoteBackLink" title="Jump back to footnote 16">↩</a></p></li>
            <li id="fn17"><p>17/ Natural Language ToolKit, Open source Python modules, linguistic data and documentation for research and development in natural language processing and text analytics. <a href="http://nltk.org">http://nltk.org</a>, <a href="http://nltk.org/book">http://nltk.org/book</a> <a href="#fnref17" class="footnoteBackLink" title="Jump back to footnote 17">↩</a></p></li>
            <li id="fn18"><p>18/ Gérard Genette, <em>Paratexts: Thresholds of Interpretation</em>, Introduction page 1, Cambridge ; New York, NY, USA : Cambridge University Press, 1997. <a href="#fnref18" class="footnoteBackLink" title="Jump back to footnote 18">↩</a></p></li>
        </ol>
    </div>
</div>


<div id="colophon">
    <h2>Colophon</h2>
    <p>
    <h3>Editorial work and experiments</h3> Nicolas Malevé, Donatella Portoghese, <a href="http://osp.constantvzw.org/">OSP</a> (Alexandre Leray, Stéphanie&nbsp;Vilayphiou, Gijs de Heij)
    </p>
    <p>
    <h3>Visual identity of V/J12</h3> <a href="http://osp.constantvzw.org/" target="_blank">OSP</a> (Ludivine Loiseau, Ivan Monroy Lopez, Pierre Marchand)
    </p>
</div>

</div>


