<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title>Hello</title>
        <link rel="stylesheet" href="http://meyerweb.com/eric/tools/css/reset/reset.css" type="text/css" media="screen" charset="utf-8">
        <style>
        html, body {
            font-size: 11px;
            line-height: 15px;
        }
        div#source, div#result {
            text-wrap: pre-line;
            font-family: Sans;
            width: 50%;
            height: 100%;
        }
        div#source {
            float: left;
        }
        div#result {
            float: right;
            font-size: 9px;
            font-family: Monospace;
        }
        div pre {
            padding: 1em;
        }
        a {
            color: inherit;
            text-decoration: inherit;
        }
        a:hover {
            background-color: yellow;
        }
        </style>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
        <script type="text/javascript" charset="utf-8">
            $(document).ready(function() {
            });
        </script>
    </head>
    <body>

<div id="source">
<pre>

'\" <a href="/context/t">t</span>
.\"
.\" <a href="/context/You">You</span> <a href="/context/may">may</span> <a href="/context/distribute">distribute</span> <a href="/context/under">under</span> <a href="/context/the">the</span> <a href="/context/terms">terms</span> <a href="/context/of">of</span> <a href="/context/the">the</span> <a href="/context/GNU">GNU</span> <a href="/context/General">General</span> <a href="/context/Public">Public</span>
.\" <a href="/context/License">License</span> <a href="/context/as">as</span> <a href="/context/specified">specified</span> <a href="/context/in">in</span> <a href="/context/the">the</span> <a href="/context/file">file</span> <a href="/context/COPYING">COPYING</span> <a href="/context/that">that</span> <a href="/context/comes">comes</span> <a href="/context/with">with</span> <a href="/context/the">the</span>
.\" <a href="/context/man">man</span>-<a href="/context/db">db</span> <a href="/context/distribution">distribution</span>.
.\"
.\" <a href="/context/Sat">Sat</span> <a href="/context/Nov">Nov</span> <a href="/context/27">27</span>
.\"
.<a href="/context/pc">pc</span>
.<a href="/context/TH">TH</span> <a href="/context/print">print</span> <a href="/context/soapbox">soapbox</span> "<a href="/context/2009">2009</span>-<a href="/context/11">11</span>-<a href="/context/28">28</span>" "<a href="/context/1">1</span>.<a href="/context/0">0</span>" "<a href="/context/print">print</span>"
.<a href="/context/SH">SH</span> <a href="/context/manuals">manuals</span>, <a href="/context/man">man</span> <a href="/context/pages">pages</span>
.<a href="/context/I">I</span> <a href="/context/according">according</span> <a href="/context/to">to</span> <a href="/context/the">the</span> <a href="/context/mmm">mmm</span>, <a href="/context/software">software</span> <a href="/context/has">has</span> <a href="/context/two">two</span> <a href="/context/faces">faces</span>, <a href="/context/both">both</span> <a href="/context/as">as</span> <a href="/context/important">important</span>. <a href="/context/the">the</span> <a href="/context/code">code</span>
.<a href="/context/I">I</span> <a href="/context/speaks">speaks</span> <a href="/context/to">to</span> <a href="/context/the">the</span> <a href="/context/machine">machine</span>, <a href="/context/and">and</span> <a href="/context/the">the</span> <a href="/context/documentation">documentation</span> ``<a href="/context/tells">tells</span> <a href="/context/its">its</span> <a href="/context/story">story</span> <a href="/context/to">to</span> <a href="/context/the">the</span> <a href="/context/human">human</span>
.<a href="/context/I">I</span> <a href="/context/user">user</span>.''

<a href="/context/The">The</span> <a href="/context/following">following</span> <a href="/context/is">is</span> <a href="/context/also">also</span> <a href="/context/from">from</span> <a href="/context/the">the</span> <a href="/context/fanzine">fanzine</span> <a href="/context/I">I</span>'<a href="/context/m">m</span> <a href="/context/talking">talking</span> <a href="/context/about">about</span>. <a href="/context/It">It</span>'<a href="/context/s">s</span> <a href="/context/a">a</span> <a href="/context/perhaps">perhaps</span>
<a href="/context/convoluted">convoluted</span> <a href="/context/way">way</span> <a href="/context/of">of</span> <a href="/context/saying">saying</span> <a href="/context/that">that</span> <a href="/context/there">there</span>'<a href="/context/s">s</span> <a href="/context/a">a</span> <a href="/context/difference">difference</span> <a href="/context/between">between</span> <a href="/context/the">the</span> <a href="/context/documents">documents</span> <a href="/context/that">that</span>
<a href="/context/keep">keep</span> <a href="/context/track">track</span> <a href="/context/of">of</span> <a href="/context/the">the</span> <a href="/context/changes">changes</span> <a href="/context/in">in</span> <a href="/context/a">a</span> <a href="/context/piece">piece</span> <a href="/context/of">of</span> <a href="/context/software">software</span> <a href="/context/over">over</span> <a href="/context/time">time</span>, <a href="/context/and">and</span> <a href="/context/the">the</span> <a href="/context/documents">documents</span>
<a href="/context/that">that</span> <a href="/context/show">show</span> <a href="/context/how">how</span> <a href="/context/a">a</span> <a href="/context/piece">piece</span> <a href="/context/of">of</span> <a href="/context/software">software</span> <a href="/context/is">is</span> <a href="/context/used">used</span>, <a href="/context/even">even</span> <a href="/context/if">if</span> <a href="/context/they">they</span> <a href="/context/sometimes">sometimes</span> <a href="/context/get">get</span> <a href="/context/lumped">lumped</span>
<a href="/context/together">together</span>. <a href="/context/Texinfo">Texinfo</span> <a href="/context/is">is</span> <a href="/context/just">just</span> <a href="/context/another">another</span> <a href="/context/documentation">documentation</span> <a href="/context/format">format</span> <a href="/context/that">that</span> <a href="/context/some">some</span> <a href="/context/people">people</span> <a href="/context/seem">seem</span>
<a href="/context/to">to</span> <a href="/context/prefer">prefer</span>.

.<a href="/context/I">I</span> <a href="/context/in">in</span> <a href="/context/the">the</span> <a href="/context/gnu">gnu</span> <a href="/context/coding">coding</span> <a href="/context/standards">standards</span>, <a href="/context/the">the</span> <a href="/context/terms">terms</span> <a href="/context/documentation">documentation</span> <a href="/context/and">and</span> <a href="/context/manual">manual</span> <a href="/context/practically">practically</span>
.<a href="/context/I">I</span> <a href="/context/mean">mean</span> <a href="/context/the">the</span> <a href="/context/same">same</span> <a href="/context/thing">thing</span>. <a href="/context/specifically">specifically</span>, <a href="/context/a">a</span> <a href="/context/manual">manual</span> <a href="/context/is">is</span> <a href="/context/a">a</span> <a href="/context/texinfo">texinfo</span> <a href="/context/file">file</span>, <a href="/context/and">and</span>
.<a href="/context/I">I</span> <a href="/context/documentation">documentation</span> <a href="/context/includes">includes</span> <a href="/context/manuals">manuals</span> <a href="/context/and">and</span> <a href="/context/other">other</span> <a href="/context/things">things</span> <a href="/context/like">like</span> <a href="/context/NEWS">NEWS</span> <a href="/context/files">files</span> <a href="/context/and">and</span> <a href="/context/change">change</span>
.<a href="/context/I">I</span> <a href="/context/logs">logs</span>. <a href="/context/in">in</span> <a href="/context/practice">practice</span>, <a href="/context/the">the</span> <a href="/context/latter">latter</span> <a href="/context/term">term</span> <a href="/context/practically">practically</span> <a href="/context/takes">takes</span> <a href="/context/the">the</span> <a href="/context/place">place</span> <a href="/context/of">of</span> <a href="/context/the">the</span> <a href="/context/former">former</span>.
.<a href="/context/I">I</span> <a href="/context/regarding">regarding</span> <a href="/context/unix">unix</span> <a href="/context/man">man</span> <a href="/context/pages">pages</span>, <a href="/context/gnu">gnu</span> <a href="/context/suggests">suggests</span> <a href="/context/that">that</span> -<a href="/context/if">if</span> <a href="/context/adequate">adequate</span>- <a href="/context/help2man">help2man</span> <a href="/context/be">be</span> <a href="/context/used">used</span> <a href="/context/to">to</span>
.<a href="/context/I">I</span> <a href="/context/extract">extract</span> <a href="/context/a">a</span> <a href="/context/man">man</span> <a href="/context/page">page</span> <a href="/context/from">from</span> <a href="/context/the">the</span> <a href="/context/texinfo">texinfo</span> <a href="/context/file">file</span>. <a href="/context/unlike">unlike</span> <a href="/context/man">man</span> <a href="/context/pages">pages</span>, <a href="/context/gnu">gnu</span> <a href="/context/manuals">manuals</span> <a href="/context/should">should</span>
.<a href="/context/I">I</span> <a href="/context/have">have</span> <a href="/context/a">a</span> ``<a href="/context/coherent">coherent</span> <a href="/context/topic">topic</span>''. <a href="/context/as">as</span> <a href="/context/an">an</span> <a href="/context/example">example</span>, <a href="/context/the">the</span> <a href="/context/coding">coding</span> <a href="/context/standards">standards</span> <a href="/context/note">note</span> <a href="/context/that">that</span> <a href="/context/diff">diff</span>
.<a href="/context/I">I</span> <a href="/context/and">and</span> <a href="/context/diff3">diff3</span> <a href="/context/are">are</span> <a href="/context/both">both</span> <a href="/context/covered">covered</span> <a href="/context/in">in</span> <a href="/context/a">a</span> <a href="/context/single">single</span> <a href="/context/manual">manual</span>, <a href="/context/whereas">whereas</span> <a href="/context/there">there</span> <a href="/context/are">are</span> <a href="/context/two">two</span> <a href="/context/man">man</span>
.<a href="/context/I">I</span> <a href="/context/pages">pages</span>, <a href="/context/one">one</span> <a href="/context/for">for</span> <a href="/context/each">each</span> <a href="/context/command">command</span>.

<a href="/context/I">I</span> <a href="/context/think">think</span> <a href="/context/that">that</span> <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/funny">funny</span> <a href="/context/that">that</span> <a href="/context/they">they</span> <a href="/context/write">write</span> <a href="/context/implementation">implementation</span> <a href="/context/does">does</span> <a href="/context/not">not</span> <a href="/context/equal">equal</span>
<a href="/context/documentation">documentation</span>. <a href="/context/I">I</span> <a href="/context/guess">guess</span> <a href="/context/that">that</span> <a href="/context/sometimes">sometimes</span> <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/hard">hard</span> <a href="/context/to">to</span> <a href="/context/take">take</span> <a href="/context/distance">distance</span>:

.<a href="/context/I">I</span> <a href="/context/the">the</span> <a href="/context/people">people</span> <a href="/context/of">of</span> <a href="/context/gnu">gnu</span> <a href="/context/distinguish">distinguish</span> <a href="/context/between">between</span> <a href="/context/the">the</span> <a href="/context/way">way</span> <a href="/context/in">in</span> <a href="/context/which">which</span> <a href="/context/a">a</span> <a href="/context/program">program</span> <a href="/context/was">was</span> <a href="/context/built">built</span>,
.<a href="/context/I">I</span> <a href="/context/and">and</span> <a href="/context/the">the</span> <a href="/context/way">way</span> <a href="/context/in">in</span> <a href="/context/which">which</span> <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/used">used</span>. <a href="/context/they">they</span> <a href="/context/warn">warn</span> <a href="/context/about">about</span> <a href="/context/modelling">modelling</span> <a href="/context/the">the</span> <a href="/context/documentation">documentation</span>
.<a href="/context/I">I</span> <a href="/context/after">after</span> <a href="/context/the">the</span> <a href="/context/software">software</span>:

.<a href="/context/B">B</span> <a href="/context/programmers">programmers</span> <a href="/context/tend">tend</span> <a href="/context/to">to</span> <a href="/context/carry">carry</span> <a href="/context/over">over</span> <a href="/context/the">the</span> <a href="/context/structure">structure</span> <a href="/context/of">of</span> <a href="/context/the">the</span> <a href="/context/program">program</span> <a href="/context/as">as</span> <a href="/context/the">the</span>
.<a href="/context/B">B</span> <a href="/context/structure">structure</span> <a href="/context/for">for</span> <a href="/context/its">its</span> <a href="/context/documentation">documentation</span>. <a href="/context/but">but</span> <a href="/context/this">this</span> <a href="/context/structure">structure</span> <a href="/context/is">is</span> <a href="/context/not">not</span> <a href="/context/necessarily">necessarily</span>
.<a href="/context/B">B</span> <a href="/context/good">good</span> <a href="/context/for">for</span> <a href="/context/explaining">explaining</span> <a href="/context/how">how</span> <a href="/context/to">to</span> <a href="/context/use">use</span> <a href="/context/the">the</span> <a href="/context/program">program</span> [...] <a href="/context/learn">learn</span> <a href="/context/to">to</span> <a href="/context/notice">notice</span> <a href="/context/when">when</span>
.<a href="/context/B">B</span> <a href="/context/you">you</span> <a href="/context/have">have</span> <a href="/context/unthinkingly">unthinkingly</span> <a href="/context/structured">structured</span> <a href="/context/the">the</span> <a href="/context/documentation">documentation</span> <a href="/context/like">like</span> <a href="/context/the">the</span>
.<a href="/context/B">B</span> <a href="/context/implementation">implementation</span>, <a href="/context/stop">stop</span> <a href="/context/yourself">yourself</span>, <a href="/context/and">and</span> <a href="/context/look">look</span> <a href="/context/for">for</span> <a href="/context/better">better</span> <a href="/context/alternatives">alternatives</span>.

.<a href="/context/I">I</span> <a href="/context/the">the</span> <a href="/context/coding">coding</span> <a href="/context/standards">standards</span> <a href="/context/advise">advise</span> <a href="/context/authors">authors</span> <a href="/context/to">to</span> <a href="/context/approach">approach</span> <a href="/context/users">users</span> <a href="/context/pedagogically">pedagogically</span>, <a href="/context/thinking">thinking</span>
.<a href="/context/I">I</span> <a href="/context/about">about</span> ``<a href="/context/the">the</span> <a href="/context/concepts">concepts</span> <a href="/context/and">and</span> <a href="/context/questions">questions</span> <a href="/context/that">that</span> <a href="/context/a">a</span> <a href="/context/user">user</span> <a href="/context/will">will</span> <a href="/context/have">have</span> <a href="/context/in">in</span> <a href="/context/mind">mind</span> <a href="/context/when">when</span> <a href="/context/reading">reading</span>
.<a href="/context/I">I</span> <a href="/context/it">it</span>.'' <a href="/context/what">what</span>'<a href="/context/s">s</span> <a href="/context/more">more</span>, <a href="/context/the">the</span> <a href="/context/manuals">manuals</span> <a href="/context/that">that</span> <a href="/context/they">they</span> <a href="/context/write">write</span> <a href="/context/should">should</span> <a href="/context/admit">admit</span> <a href="/context/two">two</span> <a href="/context/types">types</span> <a href="/context/of">of</span>
.<a href="/context/I">I</span> <a href="/context/reading">reading</span>: <a href="/context/tutorial">tutorial</span> <a href="/context/and">and</span> <a href="/context/reference">reference</span>. <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/interesting">interesting</span> <a href="/context/to">to</span> <a href="/context/note">note</span> <a href="/context/that">that</span> <a href="/context/by">by</span> <a href="/context/tutorial">tutorial</span> <a href="/context/they">they</span>
.<a href="/context/I">I</span> <a href="/context/mean">mean</span> <a href="/context/something">something</span> <a href="/context/that">that</span> <a href="/context/a">a</span> <a href="/context/user">user</span> <a href="/context/may">may</span> <a href="/context/want">want</span> <a href="/context/to">to</span> <a href="/context/read">read</span> <a href="/context/straight">straight</span> <a href="/context/through">through</span>.

<a href="/context/in">in</span> <a href="/context/this">this</span> <a href="/context/essay">essay</span>, <a href="/context/code">code</span> <a href="/context/is">is</span> <a href="/context/the">the</span> <a href="/context/textual">textual</span> <a href="/context/aspect">aspect</span> <a href="/context/of">of</span> <a href="/context/computer">computer</span> <a href="/context/technology">technology</span> <a href="/context/that">that</span> <a href="/context/may">may</span> <a href="/context/be">be</span>
<a href="/context/loaded">loaded</span> <a href="/context/up">up</span> <a href="/context/on">on</span> <a href="/context/a">a</span> <a href="/context/text">text</span> <a href="/context/editor">editor</span> <a href="/context/and">and</span> <a href="/context/easily">easily</span> <a href="/context/changed">changed</span>. <a href="/context/i">i</span>'<a href="/context/m">m</span> <a href="/context/consciously">consciously</span> <a href="/context/avoiding">avoiding</span> <a href="/context/any">any</span>
<a href="/context/discussion">discussion</span> <a href="/context/on">on</span> <a href="/context/the">the</span> <a href="/context/subject">subject</span> <a href="/context/of">of</span> <a href="/context/text">text</span> <a href="/context/editors">editors</span> -- <a href="/context/jot">jot</span> <a href="/context/down">down</span> <a href="/context/your">your</span> <a href="/context/edits">edits</span> <a href="/context/on">on</span> <a href="/context/a">a</span> <a href="/context/piece">piece</span> <a href="/context/of">of</span>
<a href="/context/paper">paper</span> <a href="/context/and">and</span> <a href="/context/then">then</span> <a href="/context/write">write</span> <a href="/context/them">them</span> <a href="/context/to">to</span> <a href="/context/newfile">newfile</span> <a href="/context/with">with</span> <a href="/context/echo">echo</span>. <a href="/context/what">what</span>'<a href="/context/s">s</span> <a href="/context/important">important</span> <a href="/context/to">to</span> <a href="/context/me">me</span> <a href="/context/is">is</span> <a href="/context/that">that</span>
<a href="/context/this">this</span> <a href="/context/be">be</span> <a href="/context/easily">easily</span> <a href="/context/accomplished">accomplished</span>. <a href="/context/with">with</span> <a href="/context/enough">enough</span> <a href="/context/time">time</span> <a href="/context/and">and</span> <a href="/context/energy">energy</span>, <a href="/context/anyone">anyone</span> <a href="/context/could">could</span> <a href="/context/write">write</span>
<a href="/context/interesting">interesting</span> <a href="/context/code">code</span>. <a href="/context/the">the</span> <a href="/context/best">best</span> <a href="/context/project">project</span> <a href="/context/would">would</span> <a href="/context/be">be</span> <a href="/context/if">if</span> <a href="/context/my">my</span> <a href="/context/grandmother">grandmother</span> <a href="/context/took">took</span> <a href="/context/the">the</span> <a href="/context/time">time</span> <a href="/context/to">to</span>
<a href="/context/re">re</span>-<a href="/context/write">write</span> <a href="/context/the">the</span> <a href="/context/linux">linux</span> <a href="/context/kernel">kernel</span> <a href="/context/from">from</span> <a href="/context/scratch">scratch</span>, <a href="/context/and">and</span> <a href="/context/if">if</span> <a href="/context/she">she</span> <a href="/context/kept">kept</span> <a href="/context/a">a</span> <a href="/context/record">record</span> <a href="/context/of">of</span> <a href="/context/her">her</span>
<a href="/context/reflections">reflections</span> <a href="/context/about">about</span> <a href="/context/code">code</span>. <a href="/context/as">as</span> <a href="/context/much">much</span> <a href="/context/as">as</span> <a href="/context/i">i</span> <a href="/context/like">like</span> <a href="/context/pierre">pierre</span> <a href="/context/menard">menard</span>, <a href="/context/this">this</span> <a href="/context/is">is</span> <a href="/context/not">not</span> <a href="/context/feasible">feasible</span>.
<a href="/context/the">the</span> <a href="/context/processes">processes</span> <a href="/context/of">of</span> <a href="/context/code">code</span> <a href="/context/should">should</span> <a href="/context/be">be</span> <a href="/context/manageable">manageable</span> <a href="/context/without">without</span> <a href="/context/the">the</span> <a href="/context/need">need</span> <a href="/context/of">of</span> <a href="/context/resorting">resorting</span> <a href="/context/to">to</span>
<a href="/context/too">too</span> <a href="/context/much">much</span> <a href="/context/external">external</span> <a href="/context/technical">technical</span> <a href="/context/support">support</span>. <a href="/context/this">this</span> <a href="/context/means">means</span> <a href="/context/that">that</span> <a href="/context/code">code</span> <a href="/context/is">is</span> <a href="/context/relative">relative</span>. <a href="/context/what">what</span>'<a href="/context/s">s</span>
<a href="/context/code">code</span> <a href="/context/for">for</span> <a href="/context/some">some</span> <a href="/context/will">will</span> <a href="/context/not">not</span> <a href="/context/be">be</span> <a href="/context/code">code</span> <a href="/context/for">for</span> <a href="/context/others">others</span>.

<a href="/context/when">when</span> <a href="/context/it">it</span> <a href="/context/comes">comes</span> <a href="/context/down">down</span> <a href="/context/to">to</span> <a href="/context/it">it</span>, <a href="/context/this">this</span> <a href="/context/means">means</span> <a href="/context/that">that</span> <a href="/context/code">code</span> <a href="/context/is">is</span> <a href="/context/text">text</span> <a href="/context/written">written</span> <a href="/context/in">in</span> <a href="/context/one">one</span> <a href="/context/of">of</span> <a href="/context/the">the</span>
<a href="/context/computer">computer</span> <a href="/context/languages">languages</span>. <a href="/context/code">code</span> <a href="/context/is">is</span> <a href="/context/the">the</span> <a href="/context/active">active</span> <a href="/context/practice">practice</span> <a href="/context/of">of</span> <a href="/context/altering">altering</span> <a href="/context/half">half</span>-<a href="/context/understood">understood</span>
<a href="/context/text">text</span> <a href="/context/files">files</span>. <a href="/context/code">code</span> <a href="/context/are">are</span> <a href="/context/the">the</span> <a href="/context/static">static</span> <a href="/context/characters">characters</span> <a href="/context/that">that</span> <a href="/context/silently">silently</span> <a href="/context/stare">stare</span> <a href="/context/back">back</span> <a href="/context/at">at</span> <a href="/context/you">you</span>,
<a href="/context/and">and</span> <a href="/context/that">that</span> <a href="/context/will">will</span> <a href="/context/not">not</span> <a href="/context/even">even</span> <a href="/context/you">you</span> <a href="/context/give">give</span> <a href="/context/the">the</span> <a href="/context/illusion">illusion</span> <a href="/context/that">that</span> <a href="/context/you">you</span>'<a href="/context/re">re</span> <a href="/context/double">double</span>-<a href="/context/guessing">guessing</span> <a href="/context/a">a</span>
<a href="/context/machine">machine</span>. <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/always">always</span> <a href="/context/evident">evident</span> <a href="/context/that">that</span> <a href="/context/someone">someone</span> <a href="/context/else">else</span> <a href="/context/was">was</span> <a href="/context/there">there</span> <a href="/context/before">before</span> <a href="/context/you">you</span>, <a href="/context/and">and</span> <a href="/context/that">that</span>
<a href="/context/that">that</span> <a href="/context/person">person</span> <a href="/context/was">was</span> <a href="/context/sloppy">sloppy</span>. <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/just">just</span> <a href="/context/a">a</span> <a href="/context/matter">matter</span> <a href="/context/of">of</span> <a href="/context/playing">playing</span> <a href="/context/along">along</span> <a href="/context/and">and</span> <a href="/context/locating">locating</span> <a href="/context/those">those</span>
<a href="/context/three">three</span> <a href="/context/characters">characters</span> <a href="/context/in">in</span> <a href="/context/a">a</span> <a href="/context/text">text</span> <a href="/context/file">file</span> <a href="/context/that">that</span> <a href="/context/will">will</span> <a href="/context/make">make</span> <a href="/context/all">all</span> <a href="/context/the">the</span> <a href="/context/difference">difference</span> <a href="/context/on">on</span> <a href="/context/whether">whether</span>
<a href="/context/your">your</span> <a href="/context/computer">computer</span> <a href="/context/can">can</span> <a href="/context/display">display</span> <a href="/context/postscript">postscript</span> <a href="/context/or">or</span> <a href="/context/whether">whether</span> <a href="/context/it">it</span> <a href="/context/will">will</span> <a href="/context/keep">keep</span> <a href="/context/that">that</span> <a href="/context/as">as</span> <a href="/context/a">a</span> <a href="/context/secret">secret</span>
<a href="/context/to">to</span> <a href="/context/itself">itself</span>. 

<a href="/context/my">my</span> <a href="/context/one">one</span> <a href="/context/year">year</span> <a href="/context/experience">experience</span> <a href="/context/as">as</span> <a href="/context/a">a</span> <a href="/context/software">software</span> <a href="/context/writer">writer</span> <a href="/context/has">has</span> <a href="/context/not">not</span> <a href="/context/been">been</span> <a href="/context/so">so</span> <a href="/context/nice">nice</span>, <a href="/context/but">but</span> <a href="/context/really">really</span>
<a href="/context/you">you</span> <a href="/context/should">should</span> <a href="/context/ask">ask</span> <a href="/context/someone">someone</span> <a href="/context/else">else</span> <a href="/context/with">with</span> <a href="/context/more">more</span> <a href="/context/experience">experience</span>. <a href="/context/i">i</span>'<a href="/context/ve">ve</span> <a href="/context/only">only</span> <a href="/context/worked">worked</span> <a href="/context/a">a</span> <a href="/context/little">little</span> <a href="/context/as">as</span>
<a href="/context/a">a</span> <a href="/context/freelancer">freelancer</span> (<a href="/context/whatever">whatever</span> <a href="/context/that">that</span> <a href="/context/means">means</span>) <a href="/context/on">on</span> <a href="/context/some">some</span> <a href="/context/random">random</span> <a href="/context/websites">websites</span>. <a href="/context/i">i</span>'<a href="/context/ve">ve</span> <a href="/context/been">been</span> <a href="/context/learning">learning</span>
<a href="/context/on">on</span> <a href="/context/the">the</span> <a href="/context/job">job</span> (<a href="/context/whatever">whatever</span> <a href="/context/that">that</span> <a href="/context/means">means</span>).

<a href="/context/there">there</span> <a href="/context/are">are</span> <a href="/context/probably">probably</span> <a href="/context/other">other</span> <a href="/context/ways">ways</span> <a href="/context/of">of</span> <a href="/context/saying">saying</span> <a href="/context/it">it</span>, <a href="/context/but">but</span> <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/also">also</span> <a href="/context/fine">fine</span> <a href="/context/to">to</span> <a href="/context/say">say</span> <a href="/context/that">that</span>
<a href="/context/i">i</span>'<a href="/context/ve">ve</span> <a href="/context/been">been</span> <a href="/context/bored">bored</span>.  <a href="/context/i">i</span> <a href="/context/don">don</span>'<a href="/context/t">t</span> <a href="/context/know">know</span> <a href="/context/why">why</span>. <a href="/context/there">there</span> <a href="/context/have">have</span> <a href="/context/been">been</span> <a href="/context/projects">projects</span> <a href="/context/i">i</span>'<a href="/context/m">m</span> <a href="/context/not">not</span> <a href="/context/ashamed">ashamed</span>
<a href="/context/of">of</span>, <a href="/context/but">but</span> <a href="/context/most">most</span> <a href="/context/of">of</span> <a href="/context/the">the</span> <a href="/context/time">time</span> <a href="/context/it">it</span> <a href="/context/hasn">hasn</span>'<a href="/context/t">t</span> <a href="/context/been">been</span> <a href="/context/like">like</span> <a href="/context/that">that</span>. <a href="/context/i">i</span> <a href="/context/wish">wish</span> <a href="/context/i">i</span> <a href="/context/could">could</span> <a href="/context/say">say</span> <a href="/context/i">i</span> <a href="/context/was">was</span>
<a href="/context/young">young</span> <a href="/context/i">i</span> <a href="/context/needed">needed</span> <a href="/context/the">the</span> <a href="/context/money">money</span> <a href="/context/but">but</span> <a href="/context/i">i</span>'<a href="/context/m">m</span> <a href="/context/not">not</span> <a href="/context/even">even</span> <a href="/context/that">that</span> <a href="/context/young">young</span> <a href="/context/anymore">anymore</span>. <a href="/context/health">health</span> <a href="/context/insurance">insurance</span>
<a href="/context/and">and</span> <a href="/context/that">that</span> <a href="/context/type">type</span> <a href="/context/of">of</span> <a href="/context/stuff">stuff</span> <a href="/context/is">is</span> <a href="/context/a">a</span> <a href="/context/work">work</span> <a href="/context/of">of</span> <a href="/context/fiction">fiction</span>. <a href="/context/my">my</span> <a href="/context/life">life</span> <a href="/context/is">is</span> <a href="/context/only">only</span> <a href="/context/as">as</span> <a href="/context/long">long</span> <a href="/context/as">as</span> <a href="/context/my">my</span>
<a href="/context/computer">computer</span>'<a href="/context/s">s</span> <a href="/context/life">life</span>.

<a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/depressing">depressing</span> <a href="/context/to">to</span> <a href="/context/see">see</span> <a href="/context/that">that</span> <a href="/context/some">some</span> <a href="/context/cliches">cliches</span> <a href="/context/are">are</span> <a href="/context/true">true</span>. <a href="/context/the">the</span> <a href="/context/offices">offices</span> <a href="/context/of">of</span> <a href="/context/lab">lab</span> <a href="/context/rats">rats</span>
<a href="/context/typing">typing</span> <a href="/context/looking">looking</span> <a href="/context/for">for</span> <a href="/context/the">the</span> <a href="/context/key">key</span> <a href="/context/of">of</span> <a href="/context/the">the</span> <a href="/context/cookie">cookie</span>, <a href="/context/waiting">waiting</span> <a href="/context/to">to</span> <a href="/context/be">be</span> <a href="/context/rewarded">rewarded</span> <a href="/context/with">with</span> <a href="/context/a">a</span>
<a href="/context/cookie">cookie</span>, <a href="/context/and">and</span> <a href="/context/kept">kept</span> <a href="/context/awake">awake</span> <a href="/context/with">with</span> <a href="/context/coffee">coffee</span>. <a href="/context/i">i</span> <a href="/context/could">could</span> <a href="/context/have">have</span> <a href="/context/passed">passed</span> <a href="/context/out">out</span> <a href="/context/in">in</span> <a href="/context/front">front</span> <a href="/context/of">of</span> <a href="/context/the">the</span>
<a href="/context/computer">computer</span> <a href="/context/and">and</span> <a href="/context/no">no</span> <a href="/context/one">one</span> <a href="/context/would">would</span> <a href="/context/have">have</span> <a href="/context/noticed">noticed</span>. <a href="/context/the">the</span> <a href="/context/feeling">feeling</span> <a href="/context/that">that</span> <a href="/context/no">no</span> <a href="/context/one">one</span> <a href="/context/knows">knows</span> <a href="/context/what">what</span>
<a href="/context/they">they</span>'<a href="/context/re">re</span> <a href="/context/doing">doing</span>. <a href="/context/the">the</span> <a href="/context/obscure">obscure</span> <a href="/context/files">files</span> <a href="/context/that">that</span> <a href="/context/you">you</span> <a href="/context/can">can</span> <a href="/context/find">find</span> <a href="/context/inside">inside</span> <a href="/context/of">of</span> <a href="/context/some">some</span> <a href="/context/computers">computers</span>.
<a href="/context/what">what</span> <a href="/context/i">i</span> <a href="/context/would">would</span> <a href="/context/do">do</span> <a href="/context/is">is</span> <a href="/context/open">open</span> <a href="/context/them">them</span> <a href="/context/for">for</span> <a href="/context/as">as</span> <a href="/context/long">long</span> <a href="/context/as">as</span> <a href="/context/i">i</span>'<a href="/context/d">d</span> <a href="/context/stand">stand</span> <a href="/context/it">it</span>, <a href="/context/close">close</span> <a href="/context/my">my</span> <a href="/context/eyes">eyes</span>, <a href="/context/press">press</span>
<a href="/context/some">some</span> <a href="/context/random">random</span> <a href="/context/keys">keys</span>, <a href="/context/close">close</span> <a href="/context/them">them</span> <a href="/context/and">and</span> <a href="/context/try">try</span> <a href="/context/to">to</span> <a href="/context/forget">forget</span> <a href="/context/about">about</span> <a href="/context/it">it</span>. <a href="/context/there">there</span>'<a href="/context/s">s</span> <a href="/context/determinacy">determinacy</span>
<a href="/context/in">in</span> <a href="/context/software">software</span> <a href="/context/insofar">insofar</span> <a href="/context/as">as</span> <a href="/context/you">you</span> <a href="/context/can">can</span> <a href="/context/work">work</span> <a href="/context/like">like</span> <a href="/context/this">this</span> <a href="/context/and">and</span> <a href="/context/nothing">nothing</span> <a href="/context/breaks">breaks</span>.

<a href="/context/i">i</span> <a href="/context/wish">wish</span> <a href="/context/i">i</span> <a href="/context/could">could</span> <a href="/context/live">live</span> <a href="/context/in">in</span> <a href="/context/a">a</span> <a href="/context/mountain">mountain</span> <a href="/context/and">and</span> <a href="/context/contemplate">contemplate</span> <a href="/context/my">my</span> <a href="/context/mark">mark</span>-<a href="/context/up">up</span>.  <a href="/context/i">i</span> <a href="/context/wish">wish</span> <a href="/context/it">it</span> <a href="/context/was">was</span>,
<a href="/context/but">but</span> <a href="/context/it">it</span> <a href="/context/can">can</span>'<a href="/context/t">t</span> <a href="/context/be">be</span> <a href="/context/and">and</span> <a href="/context/it">it</span> <a href="/context/isn">isn</span>'<a href="/context/t">t</span> <a href="/context/only">only</span> <a href="/context/about">about</span> <a href="/context/the">the</span> <a href="/context/code">code</span>. <a href="/context/if">if</span> <a href="/context/it">it</span> <a href="/context/was">was</span> <a href="/context/only">only</span> <a href="/context/about">about</span> <a href="/context/the">the</span>
<a href="/context/code">code</span>, <a href="/context/i">i</span> <a href="/context/wouldn">wouldn</span>'<a href="/context/t">t</span> <a href="/context/need">need</span> <a href="/context/to">to</span> <a href="/context/go">go</span> <a href="/context/out">out</span> <a href="/context/of">of</span> <a href="/context/my">my</span> <a href="/context/room">room</span>. <a href="/context/i">i</span> <a href="/context/don">don</span>'<a href="/context/t">t</span> <a href="/context/know">know</span> <a href="/context/what">what</span> <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/about">about</span>, <a href="/context/and">and</span> <a href="/context/i">i</span>
<a href="/context/don">don</span>'<a href="/context/t">t</span> <a href="/context/know">know</span> <a href="/context/what">what</span> <a href="/context/i">i</span>'<a href="/context/m">m</span> <a href="/context/talking">talking</span> <a href="/context/about">about</span>. <a href="/context/this">this</span> <a href="/context/is">is</span> <a href="/context/the">the</span> <a href="/context/point">point</span> <a href="/context/where">where</span> <a href="/context/i">i</span> <a href="/context/start">start</span> <a href="/context/to">to</span> <a href="/context/have">have</span>
<a href="/context/problems">problems</span> <a href="/context/finishing">finishing</span> <a href="/context/my">my</span> <a href="/context/sentences">sentences</span>. <a href="/context/likewise">likewise</span>, <a href="/context/this">this</span> <a href="/context/type">type</span> <a href="/context/of">of</span> <a href="/context/media">media</span> <a href="/context/work">work</span> <a href="/context/is">is</span> <a href="/context/complete">complete</span>
<a href="/context/nonsense">nonsense</span>. <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/absurd">absurd</span> <a href="/context/that">that</span> <a href="/context/i">i</span> <a href="/context/can">can</span>'<a href="/context/t">t</span> <a href="/context/find">find</span> <a href="/context/a">a</span> <a href="/context/job">job</span>, <a href="/context/and">and</span> <a href="/context/that">that</span> <a href="/context/i">i</span> <a href="/context/can">can</span>'<a href="/context/t">t</span> <a href="/context/hold">hold</span> <a href="/context/on">on</span> <a href="/context/to">to</span> <a href="/context/the">the</span>
<a href="/context/jobs">jobs</span> <a href="/context/that">that</span> <a href="/context/i">i</span> <a href="/context/hate">hate</span>.

<a href="/context/after">after</span> <a href="/context/one">one</span> <a href="/context/year">year</span> <a href="/context/of">of</span> <a href="/context/writing">writing</span> <a href="/context/software">software</span>, <a href="/context/it">it</span>'<a href="/context/s">s</span> <a href="/context/good">good</span> <a href="/context/to">to</span> <a href="/context/go">go</span> <a href="/context/back">back</span> <a href="/context/to">to</span> <a href="/context/the">the</span> <a href="/context/first">first</span> <a href="/context/things">things</span> <a href="/context/i">i</span>
<a href="/context/wrote">wrote</span>. <a href="/context/maybe">maybe</span> <a href="/context/there">there</span> <a href="/context/is">is</span> <a href="/context/something">something</span> <a href="/context/of">of</span> <a href="/context/crawling">crawling</span> <a href="/context/into">into</span> <a href="/context/my">my</span> <a href="/context/bed">bed</span> <a href="/context/and">and</span> <a href="/context/pulling">pulling</span> <a href="/context/up">up</span> <a href="/context/the">the</span>
<a href="/context/covers">covers</span> <a href="/context/about">about</span> <a href="/context/it">it</span>. <a href="/context/probably">probably</span> <a href="/context/not">not</span>. <a href="/context/i">i</span>'<a href="/context/m">m</span> <a href="/context/just">just</span> <a href="/context/happy">happy</span>. <a href="/context/it">it</span> <a href="/context/was">was</span> <a href="/context/great">great</span> <a href="/context/to">to</span> <a href="/context/have">have</span> <a href="/context/imagined">imagined</span>
<a href="/context/an">an</span> <a href="/context/introductory">introductory</span> <a href="/context/perl">perl</span> <a href="/context/manual">manual</span> <a href="/context/where">where</span> <a href="/context/the">the</span> <a href="/context/examples">examples</span> <a href="/context/and">and</span> <a href="/context/exercises">exercises</span> <a href="/context/deal">deal</span> <a href="/context/with">with</span>
<a href="/context/generative">generative</span> <a href="/context/groff">groff</span> <a href="/context/mark">mark</span>-<a href="/context/up">up</span>.
</pre>
</div>

<div id="result">
<pre>
{{ ptx }}
</pre>
</div>
    </body>
</html>
